/*
Codio API

Testing CourseExportsAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package codioapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_codioapi_CourseExportsAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CourseExportsAPIAPIService ExportAssessmentData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportAssessmentData(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportAssignmentCSV", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var assignmentId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportAssignmentCSV(context.Background(), courseId, assignmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportCoachData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportCoachData(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportCoachDataByTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var taskId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportCoachDataByTask(context.Background(), courseId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportCourseSourceDataItemByTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var taskId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportCourseSourceDataItemByTask(context.Background(), courseId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportCourseSourceDataItems", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportCourseSourceDataItems(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportCourseSourcesData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportCourseSourcesData(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportCourseWorkData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportCourseWorkData(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportCourseWorkDataItemByTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var taskId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportCourseWorkDataItemByTask(context.Background(), courseId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportCourseWorkDataItems", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportCourseWorkDataItems(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportLLMProxyData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportLLMProxyData(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportLLMProxyDataByTaskRoute", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var taskId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportLLMProxyDataByTaskRoute(context.Background(), courseId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService ExportStudentCSV", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var studentId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.ExportStudentCSV(context.Background(), courseId, studentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService FetchDownloadStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var taskId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.FetchDownloadStatus(context.Background(), courseId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService FetchDownloadStatusStudent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var assignmentId string
		var studentId string
		var taskId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.FetchDownloadStatusStudent(context.Background(), courseId, assignmentId, studentId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseExportsAPIAPIService StartedAssignmentDownload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var assignmentId string
		var studentId string

		resp, httpRes, err := apiClient.CourseExportsAPIAPI.StartedAssignmentDownload(context.Background(), courseId, assignmentId, studentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
