/*
Codio API

Testing CourseAssignmentsAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package codioapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_codioapi_CourseAssignmentsAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CourseAssignmentsAPIAPIService AssignmentStudentsInfo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var assignmentId string

		resp, httpRes, err := apiClient.CourseAssignmentsAPIAPI.AssignmentStudentsInfo(context.Background(), courseId, assignmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAssignmentsAPIAPIService AssignmentVersionPublish", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var assignmentId string

		resp, httpRes, err := apiClient.CourseAssignmentsAPIAPI.AssignmentVersionPublish(context.Background(), courseId, assignmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAssignmentsAPIAPIService AssignmentVersionPublishesStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var assignmentId string
		var taskId string

		resp, httpRes, err := apiClient.CourseAssignmentsAPIAPI.AssignmentVersionPublishesStatus(context.Background(), courseId, assignmentId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAssignmentsAPIAPIService CreateProjectBasedAssignment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseAssignmentsAPIAPI.CreateProjectBasedAssignment(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAssignmentsAPIAPIService FetchAssignmentSettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var assignmentId string

		resp, httpRes, err := apiClient.CourseAssignmentsAPIAPI.FetchAssignmentSettings(context.Background(), courseId, assignmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAssignmentsAPIAPIService UpdateAssignmentSettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var assignmentId string

		resp, httpRes, err := apiClient.CourseAssignmentsAPIAPI.UpdateAssignmentSettings(context.Background(), courseId, assignmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAssignmentsAPIAPIService UpdateStudentTimeExtensions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var assignmentId string
		var studentId string

		resp, httpRes, err := apiClient.CourseAssignmentsAPIAPI.UpdateStudentTimeExtensions(context.Background(), courseId, assignmentId, studentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
