/*
Codio API

Testing EventsAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package codioapi

import (
	"context"
	openapiclient "github.com/codio/codio-api-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_codioapi_EventsAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EventsAPIAPIService EventList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EventsAPIAPI.EventList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
