/*
Codio API

Testing StackAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package codioapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_codioapi_StackAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StackAPIAPIService StackInfo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stackId string

		resp, httpRes, err := apiClient.StackAPIAPI.StackInfo(context.Background(), stackId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StackAPIAPIService StackVersionsPublish", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stackId string

		resp, httpRes, err := apiClient.StackAPIAPI.StackVersionsPublish(context.Background(), stackId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StackAPIAPIService StackVersionsPublishStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stackId string
		var taskId string

		resp, httpRes, err := apiClient.StackAPIAPI.StackVersionsPublishStatus(context.Background(), stackId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
