/*
Codio API

Testing CourseAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package codioapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_codioapi_CourseAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CourseAPIAPIService ArchiveCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseAPIAPI.ArchiveCourse(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAPIAPIService CourseStructure", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseAPIAPI.CourseStructure(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAPIAPIService CoursesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CourseAPIAPI.CoursesList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAPIAPIService CreateCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CourseAPIAPI.CreateCourse(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAPIAPIService CreateCourseModule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseAPIAPI.CreateCourseModule(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAPIAPIService FilterLearnersForMentors", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseAPIAPI.FilterLearnersForMentors(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAPIAPIService FindCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CourseAPIAPI.FindCourse(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAPIAPIService ListCourseStudents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseAPIAPI.ListCourseStudents(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAPIAPIService ListCourseTeachers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseAPIAPI.ListCourseTeachers(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAPIAPIService StudentCourseProgress", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string
		var studentId string

		resp, httpRes, err := apiClient.CourseAPIAPI.StudentCourseProgress(context.Background(), courseId, studentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseAPIAPIService UpdateBooks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseAPIAPI.UpdateBooks(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
