/*
Codio API

Testing CourseBooksAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package codioapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_codioapi_CourseBooksAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CourseBooksAPIAPIService BookVersionPublish", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bookId string

		resp, httpRes, err := apiClient.CourseBooksAPIAPI.BookVersionPublish(context.Background(), bookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseBooksAPIAPIService BookVersionPublishesStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bookId string
		var taskId string

		resp, httpRes, err := apiClient.CourseBooksAPIAPI.BookVersionPublishesStatus(context.Background(), bookId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
