/*
Codio API

Testing AssessmentLibrariesAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package codioapi

import (
	"context"
	openapiclient "github.com/codio/codio-api-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_codioapi_AssessmentLibrariesAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AssessmentLibrariesAPIAPIService AssessmentLibraryCreateAssessment", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var libraryId string

		resp, httpRes, err := apiClient.AssessmentLibrariesAPIAPI.AssessmentLibraryCreateAssessment(context.Background(), libraryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssessmentLibrariesAPIAPIService AssessmentLibraryGetAssessment", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var libraryId string
		var id string

		resp, httpRes, err := apiClient.AssessmentLibrariesAPIAPI.AssessmentLibraryGetAssessment(context.Background(), libraryId, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssessmentLibrariesAPIAPIService AssessmentLibrarySearch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var libraryId string

		resp, httpRes, err := apiClient.AssessmentLibrariesAPIAPI.AssessmentLibrarySearch(context.Background(), libraryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssessmentLibrariesAPIAPIService AssessmentLibraryUpdateAssessment", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var libraryId string
		var id string

		resp, httpRes, err := apiClient.AssessmentLibrariesAPIAPI.AssessmentLibraryUpdateAssessment(context.Background(), libraryId, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssessmentLibrariesAPIAPIService ListLibraries", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.AssessmentLibrariesAPIAPI.ListLibraries(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
