/*
Codio API

Testing CourseMembersAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package codioapi

import (
	"context"
	openapiclient "github.com/codio/codio-api-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_codioapi_CourseMembersAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CourseMembersAPIAPIService AddTeacher", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var courseId string

		resp, httpRes, err := apiClient.CourseMembersAPIAPI.AddTeacher(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
