/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"os"
)


// CourseAssignmentsAPIAPIService CourseAssignmentsAPIAPI service
type CourseAssignmentsAPIAPIService service

type ApiAssignmentStudentsInfoRequest struct {
	ctx context.Context
	ApiService *CourseAssignmentsAPIAPIService
	courseId string
	assignmentId string
}

func (r ApiAssignmentStudentsInfoRequest) Execute() ([]StudentInformation, *http.Response, error) {
	return r.ApiService.AssignmentStudentsInfoExecute(r)
}

/*
AssignmentStudentsInfo Get assignment students info

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param courseId Course id
 @param assignmentId Assignment id
 @return ApiAssignmentStudentsInfoRequest
*/
func (a *CourseAssignmentsAPIAPIService) AssignmentStudentsInfo(ctx context.Context, courseId string, assignmentId string) ApiAssignmentStudentsInfoRequest {
	return ApiAssignmentStudentsInfoRequest{
		ApiService: a,
		ctx: ctx,
		courseId: courseId,
		assignmentId: assignmentId,
	}
}

// Execute executes the request
//  @return []StudentInformation
func (a *CourseAssignmentsAPIAPIService) AssignmentStudentsInfoExecute(r ApiAssignmentStudentsInfoRequest) ([]StudentInformation, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []StudentInformation
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CourseAssignmentsAPIAPIService.AssignmentStudentsInfo")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/courses/{courseId}/assignments/{assignmentId}/students"
	localVarPath = strings.Replace(localVarPath, "{"+"courseId"+"}", url.PathEscape(parameterValueToString(r.courseId, "courseId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"assignmentId"+"}", url.PathEscape(parameterValueToString(r.assignmentId, "assignmentId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAssignmentVersionPublishRequest struct {
	ctx context.Context
	ApiService *CourseAssignmentsAPIAPIService
	courseId string
	assignmentId string
	file *os.File
	changelog *string
	stackVersionId *string
	withStackUpdate *bool
}

// File archive data to be published
func (r ApiAssignmentVersionPublishRequest) File(file *os.File) ApiAssignmentVersionPublishRequest {
	r.file = file
	return r
}

// Publish changelog
func (r ApiAssignmentVersionPublishRequest) Changelog(changelog string) ApiAssignmentVersionPublishRequest {
	r.changelog = &changelog
	return r
}

// Stack version identification
func (r ApiAssignmentVersionPublishRequest) StackVersionId(stackVersionId string) ApiAssignmentVersionPublishRequest {
	r.stackVersionId = &stackVersionId
	return r
}

// Propagate stack update
func (r ApiAssignmentVersionPublishRequest) WithStackUpdate(withStackUpdate bool) ApiAssignmentVersionPublishRequest {
	r.withStackUpdate = &withStackUpdate
	return r
}

func (r ApiAssignmentVersionPublishRequest) Execute() (*TaskProgress, *http.Response, error) {
	return r.ApiService.AssignmentVersionPublishExecute(r)
}

/*
AssignmentVersionPublish Publish new assignment version

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param courseId Course id
 @param assignmentId Assignment id
 @return ApiAssignmentVersionPublishRequest
*/
func (a *CourseAssignmentsAPIAPIService) AssignmentVersionPublish(ctx context.Context, courseId string, assignmentId string) ApiAssignmentVersionPublishRequest {
	return ApiAssignmentVersionPublishRequest{
		ApiService: a,
		ctx: ctx,
		courseId: courseId,
		assignmentId: assignmentId,
	}
}

// Execute executes the request
//  @return TaskProgress
func (a *CourseAssignmentsAPIAPIService) AssignmentVersionPublishExecute(r ApiAssignmentVersionPublishRequest) (*TaskProgress, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TaskProgress
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CourseAssignmentsAPIAPIService.AssignmentVersionPublish")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/courses/{courseId}/assignments/{assignmentId}/versions"
	localVarPath = strings.Replace(localVarPath, "{"+"courseId"+"}", url.PathEscape(parameterValueToString(r.courseId, "courseId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"assignmentId"+"}", url.PathEscape(parameterValueToString(r.assignmentId, "assignmentId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	var fileLocalVarFormFileName string
	var fileLocalVarFileName     string
	var fileLocalVarFileBytes    []byte

	fileLocalVarFormFileName = "file"
	fileLocalVarFile := r.file

	if fileLocalVarFile != nil {
		fbs, _ := io.ReadAll(fileLocalVarFile)

		fileLocalVarFileBytes = fbs
		fileLocalVarFileName = fileLocalVarFile.Name()
		fileLocalVarFile.Close()
		formFiles = append(formFiles, formFile{fileBytes: fileLocalVarFileBytes, fileName: fileLocalVarFileName, formFileName: fileLocalVarFormFileName})
	}
	if r.changelog != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "changelog", r.changelog, "", "")
	}
	if r.stackVersionId != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "stackVersionId", r.stackVersionId, "", "")
	}
	if r.withStackUpdate != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "withStackUpdate", r.withStackUpdate, "", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAssignmentVersionPublishesStatusRequest struct {
	ctx context.Context
	ApiService *CourseAssignmentsAPIAPIService
	courseId string
	assignmentId string
	taskId string
}

func (r ApiAssignmentVersionPublishesStatusRequest) Execute() (*TaskStatus, *http.Response, error) {
	return r.ApiService.AssignmentVersionPublishesStatusExecute(r)
}

/*
AssignmentVersionPublishesStatus Get assignment publish status

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param courseId Course id
 @param assignmentId Assignment id
 @param taskId Task id
 @return ApiAssignmentVersionPublishesStatusRequest
*/
func (a *CourseAssignmentsAPIAPIService) AssignmentVersionPublishesStatus(ctx context.Context, courseId string, assignmentId string, taskId string) ApiAssignmentVersionPublishesStatusRequest {
	return ApiAssignmentVersionPublishesStatusRequest{
		ApiService: a,
		ctx: ctx,
		courseId: courseId,
		assignmentId: assignmentId,
		taskId: taskId,
	}
}

// Execute executes the request
//  @return TaskStatus
func (a *CourseAssignmentsAPIAPIService) AssignmentVersionPublishesStatusExecute(r ApiAssignmentVersionPublishesStatusRequest) (*TaskStatus, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TaskStatus
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CourseAssignmentsAPIAPIService.AssignmentVersionPublishesStatus")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/courses/{courseId}/assignments/{assignmentId}/publishes/{taskId}"
	localVarPath = strings.Replace(localVarPath, "{"+"courseId"+"}", url.PathEscape(parameterValueToString(r.courseId, "courseId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"assignmentId"+"}", url.PathEscape(parameterValueToString(r.assignmentId, "assignmentId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"taskId"+"}", url.PathEscape(parameterValueToString(r.taskId, "taskId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateProjectBasedAssignmentRequest struct {
	ctx context.Context
	ApiService *CourseAssignmentsAPIAPIService
	courseId string
	createAssignment *CreateAssignment
}

func (r ApiCreateProjectBasedAssignmentRequest) CreateAssignment(createAssignment CreateAssignment) ApiCreateProjectBasedAssignmentRequest {
	r.createAssignment = &createAssignment
	return r
}

func (r ApiCreateProjectBasedAssignmentRequest) Execute() (*CreateAssignmentAnswer, *http.Response, error) {
	return r.ApiService.CreateProjectBasedAssignmentExecute(r)
}

/*
CreateProjectBasedAssignment Create Project Based Assignment

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param courseId Course id
 @return ApiCreateProjectBasedAssignmentRequest
*/
func (a *CourseAssignmentsAPIAPIService) CreateProjectBasedAssignment(ctx context.Context, courseId string) ApiCreateProjectBasedAssignmentRequest {
	return ApiCreateProjectBasedAssignmentRequest{
		ApiService: a,
		ctx: ctx,
		courseId: courseId,
	}
}

// Execute executes the request
//  @return CreateAssignmentAnswer
func (a *CourseAssignmentsAPIAPIService) CreateProjectBasedAssignmentExecute(r ApiCreateProjectBasedAssignmentRequest) (*CreateAssignmentAnswer, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CreateAssignmentAnswer
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CourseAssignmentsAPIAPIService.CreateProjectBasedAssignment")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/courses/{courseId}/assignments"
	localVarPath = strings.Replace(localVarPath, "{"+"courseId"+"}", url.PathEscape(parameterValueToString(r.courseId, "courseId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createAssignment
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiFetchAssignmentSettingsRequest struct {
	ctx context.Context
	ApiService *CourseAssignmentsAPIAPIService
	courseId string
	assignmentId string
}

func (r ApiFetchAssignmentSettingsRequest) Execute() (*AssignmentSettingsResult, *http.Response, error) {
	return r.ApiService.FetchAssignmentSettingsExecute(r)
}

/*
FetchAssignmentSettings Fetch Assignment Settings

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param courseId Course id
 @param assignmentId Assignment id
 @return ApiFetchAssignmentSettingsRequest
*/
func (a *CourseAssignmentsAPIAPIService) FetchAssignmentSettings(ctx context.Context, courseId string, assignmentId string) ApiFetchAssignmentSettingsRequest {
	return ApiFetchAssignmentSettingsRequest{
		ApiService: a,
		ctx: ctx,
		courseId: courseId,
		assignmentId: assignmentId,
	}
}

// Execute executes the request
//  @return AssignmentSettingsResult
func (a *CourseAssignmentsAPIAPIService) FetchAssignmentSettingsExecute(r ApiFetchAssignmentSettingsRequest) (*AssignmentSettingsResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AssignmentSettingsResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CourseAssignmentsAPIAPIService.FetchAssignmentSettings")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/courses/{courseId}/assignments/{assignmentId}/settings"
	localVarPath = strings.Replace(localVarPath, "{"+"courseId"+"}", url.PathEscape(parameterValueToString(r.courseId, "courseId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"assignmentId"+"}", url.PathEscape(parameterValueToString(r.assignmentId, "assignmentId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateAssignmentSettingsRequest struct {
	ctx context.Context
	ApiService *CourseAssignmentsAPIAPIService
	courseId string
	assignmentId string
	assignmentSettings *AssignmentSettings
}

func (r ApiUpdateAssignmentSettingsRequest) AssignmentSettings(assignmentSettings AssignmentSettings) ApiUpdateAssignmentSettingsRequest {
	r.assignmentSettings = &assignmentSettings
	return r
}

func (r ApiUpdateAssignmentSettingsRequest) Execute() (*AssignmentSettingsResult, *http.Response, error) {
	return r.ApiService.UpdateAssignmentSettingsExecute(r)
}

/*
UpdateAssignmentSettings Update Assignment Settings

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param courseId Course id
 @param assignmentId Assignment id
 @return ApiUpdateAssignmentSettingsRequest
*/
func (a *CourseAssignmentsAPIAPIService) UpdateAssignmentSettings(ctx context.Context, courseId string, assignmentId string) ApiUpdateAssignmentSettingsRequest {
	return ApiUpdateAssignmentSettingsRequest{
		ApiService: a,
		ctx: ctx,
		courseId: courseId,
		assignmentId: assignmentId,
	}
}

// Execute executes the request
//  @return AssignmentSettingsResult
func (a *CourseAssignmentsAPIAPIService) UpdateAssignmentSettingsExecute(r ApiUpdateAssignmentSettingsRequest) (*AssignmentSettingsResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AssignmentSettingsResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CourseAssignmentsAPIAPIService.UpdateAssignmentSettings")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/courses/{courseId}/assignments/{assignmentId}/settings"
	localVarPath = strings.Replace(localVarPath, "{"+"courseId"+"}", url.PathEscape(parameterValueToString(r.courseId, "courseId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"assignmentId"+"}", url.PathEscape(parameterValueToString(r.assignmentId, "assignmentId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.assignmentSettings
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateStudentTimeExtensionsRequest struct {
	ctx context.Context
	ApiService *CourseAssignmentsAPIAPIService
	courseId string
	assignmentId string
	studentId string
	studentTimeExtension *StudentTimeExtension
}

func (r ApiUpdateStudentTimeExtensionsRequest) StudentTimeExtension(studentTimeExtension StudentTimeExtension) ApiUpdateStudentTimeExtensionsRequest {
	r.studentTimeExtension = &studentTimeExtension
	return r
}

func (r ApiUpdateStudentTimeExtensionsRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.UpdateStudentTimeExtensionsExecute(r)
}

/*
UpdateStudentTimeExtensions Update Student Time Extensions

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param courseId Course id
 @param assignmentId Assignment id
 @param studentId Student id
 @return ApiUpdateStudentTimeExtensionsRequest
*/
func (a *CourseAssignmentsAPIAPIService) UpdateStudentTimeExtensions(ctx context.Context, courseId string, assignmentId string, studentId string) ApiUpdateStudentTimeExtensionsRequest {
	return ApiUpdateStudentTimeExtensionsRequest{
		ApiService: a,
		ctx: ctx,
		courseId: courseId,
		assignmentId: assignmentId,
		studentId: studentId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *CourseAssignmentsAPIAPIService) UpdateStudentTimeExtensionsExecute(r ApiUpdateStudentTimeExtensionsRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CourseAssignmentsAPIAPIService.UpdateStudentTimeExtensions")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/courses/{courseId}/assignments/{assignmentId}/students/{studentId}"
	localVarPath = strings.Replace(localVarPath, "{"+"courseId"+"}", url.PathEscape(parameterValueToString(r.courseId, "courseId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"assignmentId"+"}", url.PathEscape(parameterValueToString(r.assignmentId, "assignmentId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"studentId"+"}", url.PathEscape(parameterValueToString(r.studentId, "studentId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.studentTimeExtension
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
