/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"os"
)


// CourseBooksAPIAPIService CourseBooksAPIAPI service
type CourseBooksAPIAPIService service

type ApiBookVersionPublishRequest struct {
	ctx context.Context
	ApiService *CourseBooksAPIAPIService
	bookId string
	file *os.File
	changelog *string
	stackVersionId *string
	withStackUpdate *bool
}

// File archive data to be published
func (r ApiBookVersionPublishRequest) File(file *os.File) ApiBookVersionPublishRequest {
	r.file = file
	return r
}

// Publish changelog
func (r ApiBookVersionPublishRequest) Changelog(changelog string) ApiBookVersionPublishRequest {
	r.changelog = &changelog
	return r
}

// Stack version identification
func (r ApiBookVersionPublishRequest) StackVersionId(stackVersionId string) ApiBookVersionPublishRequest {
	r.stackVersionId = &stackVersionId
	return r
}

// Propagate stack update
func (r ApiBookVersionPublishRequest) WithStackUpdate(withStackUpdate bool) ApiBookVersionPublishRequest {
	r.withStackUpdate = &withStackUpdate
	return r
}

func (r ApiBookVersionPublishRequest) Execute() (*TaskProgress, *http.Response, error) {
	return r.ApiService.BookVersionPublishExecute(r)
}

/*
BookVersionPublish Publish new book version

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param bookId Book id
 @return ApiBookVersionPublishRequest
*/
func (a *CourseBooksAPIAPIService) BookVersionPublish(ctx context.Context, bookId string) ApiBookVersionPublishRequest {
	return ApiBookVersionPublishRequest{
		ApiService: a,
		ctx: ctx,
		bookId: bookId,
	}
}

// Execute executes the request
//  @return TaskProgress
func (a *CourseBooksAPIAPIService) BookVersionPublishExecute(r ApiBookVersionPublishRequest) (*TaskProgress, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TaskProgress
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CourseBooksAPIAPIService.BookVersionPublish")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/books/{bookId}/versions"
	localVarPath = strings.Replace(localVarPath, "{"+"bookId"+"}", url.PathEscape(parameterValueToString(r.bookId, "bookId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	var fileLocalVarFormFileName string
	var fileLocalVarFileName     string
	var fileLocalVarFileBytes    []byte

	fileLocalVarFormFileName = "file"
	fileLocalVarFile := r.file

	if fileLocalVarFile != nil {
		fbs, _ := io.ReadAll(fileLocalVarFile)

		fileLocalVarFileBytes = fbs
		fileLocalVarFileName = fileLocalVarFile.Name()
		fileLocalVarFile.Close()
		formFiles = append(formFiles, formFile{fileBytes: fileLocalVarFileBytes, fileName: fileLocalVarFileName, formFileName: fileLocalVarFormFileName})
	}
	if r.changelog != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "changelog", r.changelog, "", "")
	}
	if r.stackVersionId != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "stackVersionId", r.stackVersionId, "", "")
	}
	if r.withStackUpdate != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "withStackUpdate", r.withStackUpdate, "", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiBookVersionPublishesStatusRequest struct {
	ctx context.Context
	ApiService *CourseBooksAPIAPIService
	bookId string
	taskId string
}

func (r ApiBookVersionPublishesStatusRequest) Execute() (*TaskStatus, *http.Response, error) {
	return r.ApiService.BookVersionPublishesStatusExecute(r)
}

/*
BookVersionPublishesStatus Get book publish status

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param bookId Book id
 @param taskId Task id
 @return ApiBookVersionPublishesStatusRequest
*/
func (a *CourseBooksAPIAPIService) BookVersionPublishesStatus(ctx context.Context, bookId string, taskId string) ApiBookVersionPublishesStatusRequest {
	return ApiBookVersionPublishesStatusRequest{
		ApiService: a,
		ctx: ctx,
		bookId: bookId,
		taskId: taskId,
	}
}

// Execute executes the request
//  @return TaskStatus
func (a *CourseBooksAPIAPIService) BookVersionPublishesStatusExecute(r ApiBookVersionPublishesStatusRequest) (*TaskStatus, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TaskStatus
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CourseBooksAPIAPIService.BookVersionPublishesStatus")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/books/{bookId}/publishes/{taskId}"
	localVarPath = strings.Replace(localVarPath, "{"+"bookId"+"}", url.PathEscape(parameterValueToString(r.bookId, "bookId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"taskId"+"}", url.PathEscape(parameterValueToString(r.taskId, "taskId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
