/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the Course type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Course{}

// Course struct for Course
type Course struct {
	// Course name
	Name *string `json:"name,omitempty"`
	// Course description
	Description *string `json:"description,omitempty"`
	// Course start date, ISO Date String
	Start *string `json:"start,omitempty"`
	// Course end date, ISO Date String
	End *string `json:"end,omitempty"`
	// Course timezone
	Timezone *string `json:"timezone,omitempty"`
	// Course tags
	Tags []string `json:"tags,omitempty"`
	// Course identifier
	Id *string `json:"id,omitempty"`
	Modules []Module `json:"modules,omitempty"`
	// Course create date, ISO Date String
	CreationDate *string `json:"creationDate,omitempty"`
	// Course archive date, ISO Date String
	ArchivedDate *string `json:"archivedDate,omitempty"`
	// Archived course state
	Archived *bool `json:"archived,omitempty"`
}

// NewCourse instantiates a new Course object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCourse() *Course {
	this := Course{}
	return &this
}

// NewCourseWithDefaults instantiates a new Course object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCourseWithDefaults() *Course {
	this := Course{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Course) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Course) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Course) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Course) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Course) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Course) SetDescription(v string) {
	o.Description = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *Course) GetStart() string {
	if o == nil || IsNil(o.Start) {
		var ret string
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetStartOk() (*string, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *Course) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given string and assigns it to the Start field.
func (o *Course) SetStart(v string) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *Course) GetEnd() string {
	if o == nil || IsNil(o.End) {
		var ret string
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetEndOk() (*string, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *Course) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given string and assigns it to the End field.
func (o *Course) SetEnd(v string) {
	o.End = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *Course) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *Course) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *Course) SetTimezone(v string) {
	o.Timezone = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Course) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Course) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Course) SetTags(v []string) {
	o.Tags = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Course) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Course) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Course) SetId(v string) {
	o.Id = &v
}

// GetModules returns the Modules field value if set, zero value otherwise.
func (o *Course) GetModules() []Module {
	if o == nil || IsNil(o.Modules) {
		var ret []Module
		return ret
	}
	return o.Modules
}

// GetModulesOk returns a tuple with the Modules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetModulesOk() ([]Module, bool) {
	if o == nil || IsNil(o.Modules) {
		return nil, false
	}
	return o.Modules, true
}

// HasModules returns a boolean if a field has been set.
func (o *Course) HasModules() bool {
	if o != nil && !IsNil(o.Modules) {
		return true
	}

	return false
}

// SetModules gets a reference to the given []Module and assigns it to the Modules field.
func (o *Course) SetModules(v []Module) {
	o.Modules = v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *Course) GetCreationDate() string {
	if o == nil || IsNil(o.CreationDate) {
		var ret string
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetCreationDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *Course) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given string and assigns it to the CreationDate field.
func (o *Course) SetCreationDate(v string) {
	o.CreationDate = &v
}

// GetArchivedDate returns the ArchivedDate field value if set, zero value otherwise.
func (o *Course) GetArchivedDate() string {
	if o == nil || IsNil(o.ArchivedDate) {
		var ret string
		return ret
	}
	return *o.ArchivedDate
}

// GetArchivedDateOk returns a tuple with the ArchivedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetArchivedDateOk() (*string, bool) {
	if o == nil || IsNil(o.ArchivedDate) {
		return nil, false
	}
	return o.ArchivedDate, true
}

// HasArchivedDate returns a boolean if a field has been set.
func (o *Course) HasArchivedDate() bool {
	if o != nil && !IsNil(o.ArchivedDate) {
		return true
	}

	return false
}

// SetArchivedDate gets a reference to the given string and assigns it to the ArchivedDate field.
func (o *Course) SetArchivedDate(v string) {
	o.ArchivedDate = &v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *Course) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Course) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *Course) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *Course) SetArchived(v bool) {
	o.Archived = &v
}

func (o Course) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Course) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Modules) {
		toSerialize["modules"] = o.Modules
	}
	if !IsNil(o.CreationDate) {
		toSerialize["creationDate"] = o.CreationDate
	}
	if !IsNil(o.ArchivedDate) {
		toSerialize["archivedDate"] = o.ArchivedDate
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	return toSerialize, nil
}

type NullableCourse struct {
	value *Course
	isSet bool
}

func (v NullableCourse) Get() *Course {
	return v.value
}

func (v *NullableCourse) Set(val *Course) {
	v.value = val
	v.isSet = true
}

func (v NullableCourse) IsSet() bool {
	return v.isSet
}

func (v *NullableCourse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCourse(val *Course) *NullableCourse {
	return &NullableCourse{value: val, isSet: true}
}

func (v NullableCourse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCourse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


