/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the RestrictedIPRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestrictedIPRange{}

// RestrictedIPRange struct for RestrictedIPRange
type RestrictedIPRange struct {
	Enabled *bool `json:"enabled,omitempty"`
	// Each ip from new line. Can specify IP or subnet.
	Range *string `json:"range,omitempty"`
}

// NewRestrictedIPRange instantiates a new RestrictedIPRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestrictedIPRange() *RestrictedIPRange {
	this := RestrictedIPRange{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// NewRestrictedIPRangeWithDefaults instantiates a new RestrictedIPRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestrictedIPRangeWithDefaults() *RestrictedIPRange {
	this := RestrictedIPRange{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *RestrictedIPRange) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestrictedIPRange) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *RestrictedIPRange) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *RestrictedIPRange) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetRange returns the Range field value if set, zero value otherwise.
func (o *RestrictedIPRange) GetRange() string {
	if o == nil || IsNil(o.Range) {
		var ret string
		return ret
	}
	return *o.Range
}

// GetRangeOk returns a tuple with the Range field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestrictedIPRange) GetRangeOk() (*string, bool) {
	if o == nil || IsNil(o.Range) {
		return nil, false
	}
	return o.Range, true
}

// HasRange returns a boolean if a field has been set.
func (o *RestrictedIPRange) HasRange() bool {
	if o != nil && !IsNil(o.Range) {
		return true
	}

	return false
}

// SetRange gets a reference to the given string and assigns it to the Range field.
func (o *RestrictedIPRange) SetRange(v string) {
	o.Range = &v
}

func (o RestrictedIPRange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestrictedIPRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Range) {
		toSerialize["range"] = o.Range
	}
	return toSerialize, nil
}

type NullableRestrictedIPRange struct {
	value *RestrictedIPRange
	isSet bool
}

func (v NullableRestrictedIPRange) Get() *RestrictedIPRange {
	return v.value
}

func (v *NullableRestrictedIPRange) Set(val *RestrictedIPRange) {
	v.value = val
	v.isSet = true
}

func (v NullableRestrictedIPRange) IsSet() bool {
	return v.isSet
}

func (v *NullableRestrictedIPRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestrictedIPRange(val *RestrictedIPRange) *NullableRestrictedIPRange {
	return &NullableRestrictedIPRange{value: val, isSet: true}
}

func (v NullableRestrictedIPRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestrictedIPRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


