/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
	"time"
)

// checks if the StudentInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StudentInformation{}

// StudentInformation struct for StudentInformation
type StudentInformation struct {
	// Student identification
	StudentId *string `json:"student_id,omitempty"`
	// Student email if available
	StudentEmail *string `json:"student_email,omitempty"`
	// Student actual name
	StudentName *string `json:"student_name,omitempty"`
	// Seconds spent in the assignment
	SecondsSpent *int32 `json:"seconds_spent,omitempty"`
	// Optional assignment grade, 0-100
	Grade *int32 `json:"grade,omitempty"`
	// Optional extra points
	ExtraCredit *int32 `json:"extra_credit,omitempty"`
	// Assignment status: STARTED, NOT_STARTED, COMPLETED
	Status *string `json:"status,omitempty"`
	// Assignment completion date, ISO Date String
	CompletionDate *time.Time `json:"completion_date,omitempty"`
	// Extended deadline
	ExtendedDeadline *int32 `json:"extendedDeadline,omitempty"`
	// Extended time limit
	ExtendedTimeLimit *int32 `json:"extendedTimeLimit,omitempty"`
}

// NewStudentInformation instantiates a new StudentInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStudentInformation() *StudentInformation {
	this := StudentInformation{}
	return &this
}

// NewStudentInformationWithDefaults instantiates a new StudentInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStudentInformationWithDefaults() *StudentInformation {
	this := StudentInformation{}
	return &this
}

// GetStudentId returns the StudentId field value if set, zero value otherwise.
func (o *StudentInformation) GetStudentId() string {
	if o == nil || IsNil(o.StudentId) {
		var ret string
		return ret
	}
	return *o.StudentId
}

// GetStudentIdOk returns a tuple with the StudentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentInformation) GetStudentIdOk() (*string, bool) {
	if o == nil || IsNil(o.StudentId) {
		return nil, false
	}
	return o.StudentId, true
}

// HasStudentId returns a boolean if a field has been set.
func (o *StudentInformation) HasStudentId() bool {
	if o != nil && !IsNil(o.StudentId) {
		return true
	}

	return false
}

// SetStudentId gets a reference to the given string and assigns it to the StudentId field.
func (o *StudentInformation) SetStudentId(v string) {
	o.StudentId = &v
}

// GetStudentEmail returns the StudentEmail field value if set, zero value otherwise.
func (o *StudentInformation) GetStudentEmail() string {
	if o == nil || IsNil(o.StudentEmail) {
		var ret string
		return ret
	}
	return *o.StudentEmail
}

// GetStudentEmailOk returns a tuple with the StudentEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentInformation) GetStudentEmailOk() (*string, bool) {
	if o == nil || IsNil(o.StudentEmail) {
		return nil, false
	}
	return o.StudentEmail, true
}

// HasStudentEmail returns a boolean if a field has been set.
func (o *StudentInformation) HasStudentEmail() bool {
	if o != nil && !IsNil(o.StudentEmail) {
		return true
	}

	return false
}

// SetStudentEmail gets a reference to the given string and assigns it to the StudentEmail field.
func (o *StudentInformation) SetStudentEmail(v string) {
	o.StudentEmail = &v
}

// GetStudentName returns the StudentName field value if set, zero value otherwise.
func (o *StudentInformation) GetStudentName() string {
	if o == nil || IsNil(o.StudentName) {
		var ret string
		return ret
	}
	return *o.StudentName
}

// GetStudentNameOk returns a tuple with the StudentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentInformation) GetStudentNameOk() (*string, bool) {
	if o == nil || IsNil(o.StudentName) {
		return nil, false
	}
	return o.StudentName, true
}

// HasStudentName returns a boolean if a field has been set.
func (o *StudentInformation) HasStudentName() bool {
	if o != nil && !IsNil(o.StudentName) {
		return true
	}

	return false
}

// SetStudentName gets a reference to the given string and assigns it to the StudentName field.
func (o *StudentInformation) SetStudentName(v string) {
	o.StudentName = &v
}

// GetSecondsSpent returns the SecondsSpent field value if set, zero value otherwise.
func (o *StudentInformation) GetSecondsSpent() int32 {
	if o == nil || IsNil(o.SecondsSpent) {
		var ret int32
		return ret
	}
	return *o.SecondsSpent
}

// GetSecondsSpentOk returns a tuple with the SecondsSpent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentInformation) GetSecondsSpentOk() (*int32, bool) {
	if o == nil || IsNil(o.SecondsSpent) {
		return nil, false
	}
	return o.SecondsSpent, true
}

// HasSecondsSpent returns a boolean if a field has been set.
func (o *StudentInformation) HasSecondsSpent() bool {
	if o != nil && !IsNil(o.SecondsSpent) {
		return true
	}

	return false
}

// SetSecondsSpent gets a reference to the given int32 and assigns it to the SecondsSpent field.
func (o *StudentInformation) SetSecondsSpent(v int32) {
	o.SecondsSpent = &v
}

// GetGrade returns the Grade field value if set, zero value otherwise.
func (o *StudentInformation) GetGrade() int32 {
	if o == nil || IsNil(o.Grade) {
		var ret int32
		return ret
	}
	return *o.Grade
}

// GetGradeOk returns a tuple with the Grade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentInformation) GetGradeOk() (*int32, bool) {
	if o == nil || IsNil(o.Grade) {
		return nil, false
	}
	return o.Grade, true
}

// HasGrade returns a boolean if a field has been set.
func (o *StudentInformation) HasGrade() bool {
	if o != nil && !IsNil(o.Grade) {
		return true
	}

	return false
}

// SetGrade gets a reference to the given int32 and assigns it to the Grade field.
func (o *StudentInformation) SetGrade(v int32) {
	o.Grade = &v
}

// GetExtraCredit returns the ExtraCredit field value if set, zero value otherwise.
func (o *StudentInformation) GetExtraCredit() int32 {
	if o == nil || IsNil(o.ExtraCredit) {
		var ret int32
		return ret
	}
	return *o.ExtraCredit
}

// GetExtraCreditOk returns a tuple with the ExtraCredit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentInformation) GetExtraCreditOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtraCredit) {
		return nil, false
	}
	return o.ExtraCredit, true
}

// HasExtraCredit returns a boolean if a field has been set.
func (o *StudentInformation) HasExtraCredit() bool {
	if o != nil && !IsNil(o.ExtraCredit) {
		return true
	}

	return false
}

// SetExtraCredit gets a reference to the given int32 and assigns it to the ExtraCredit field.
func (o *StudentInformation) SetExtraCredit(v int32) {
	o.ExtraCredit = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *StudentInformation) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentInformation) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *StudentInformation) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *StudentInformation) SetStatus(v string) {
	o.Status = &v
}

// GetCompletionDate returns the CompletionDate field value if set, zero value otherwise.
func (o *StudentInformation) GetCompletionDate() time.Time {
	if o == nil || IsNil(o.CompletionDate) {
		var ret time.Time
		return ret
	}
	return *o.CompletionDate
}

// GetCompletionDateOk returns a tuple with the CompletionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentInformation) GetCompletionDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletionDate) {
		return nil, false
	}
	return o.CompletionDate, true
}

// HasCompletionDate returns a boolean if a field has been set.
func (o *StudentInformation) HasCompletionDate() bool {
	if o != nil && !IsNil(o.CompletionDate) {
		return true
	}

	return false
}

// SetCompletionDate gets a reference to the given time.Time and assigns it to the CompletionDate field.
func (o *StudentInformation) SetCompletionDate(v time.Time) {
	o.CompletionDate = &v
}

// GetExtendedDeadline returns the ExtendedDeadline field value if set, zero value otherwise.
func (o *StudentInformation) GetExtendedDeadline() int32 {
	if o == nil || IsNil(o.ExtendedDeadline) {
		var ret int32
		return ret
	}
	return *o.ExtendedDeadline
}

// GetExtendedDeadlineOk returns a tuple with the ExtendedDeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentInformation) GetExtendedDeadlineOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtendedDeadline) {
		return nil, false
	}
	return o.ExtendedDeadline, true
}

// HasExtendedDeadline returns a boolean if a field has been set.
func (o *StudentInformation) HasExtendedDeadline() bool {
	if o != nil && !IsNil(o.ExtendedDeadline) {
		return true
	}

	return false
}

// SetExtendedDeadline gets a reference to the given int32 and assigns it to the ExtendedDeadline field.
func (o *StudentInformation) SetExtendedDeadline(v int32) {
	o.ExtendedDeadline = &v
}

// GetExtendedTimeLimit returns the ExtendedTimeLimit field value if set, zero value otherwise.
func (o *StudentInformation) GetExtendedTimeLimit() int32 {
	if o == nil || IsNil(o.ExtendedTimeLimit) {
		var ret int32
		return ret
	}
	return *o.ExtendedTimeLimit
}

// GetExtendedTimeLimitOk returns a tuple with the ExtendedTimeLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentInformation) GetExtendedTimeLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtendedTimeLimit) {
		return nil, false
	}
	return o.ExtendedTimeLimit, true
}

// HasExtendedTimeLimit returns a boolean if a field has been set.
func (o *StudentInformation) HasExtendedTimeLimit() bool {
	if o != nil && !IsNil(o.ExtendedTimeLimit) {
		return true
	}

	return false
}

// SetExtendedTimeLimit gets a reference to the given int32 and assigns it to the ExtendedTimeLimit field.
func (o *StudentInformation) SetExtendedTimeLimit(v int32) {
	o.ExtendedTimeLimit = &v
}

func (o StudentInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StudentInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StudentId) {
		toSerialize["student_id"] = o.StudentId
	}
	if !IsNil(o.StudentEmail) {
		toSerialize["student_email"] = o.StudentEmail
	}
	if !IsNil(o.StudentName) {
		toSerialize["student_name"] = o.StudentName
	}
	if !IsNil(o.SecondsSpent) {
		toSerialize["seconds_spent"] = o.SecondsSpent
	}
	if !IsNil(o.Grade) {
		toSerialize["grade"] = o.Grade
	}
	if !IsNil(o.ExtraCredit) {
		toSerialize["extra_credit"] = o.ExtraCredit
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CompletionDate) {
		toSerialize["completion_date"] = o.CompletionDate
	}
	if !IsNil(o.ExtendedDeadline) {
		toSerialize["extendedDeadline"] = o.ExtendedDeadline
	}
	if !IsNil(o.ExtendedTimeLimit) {
		toSerialize["extendedTimeLimit"] = o.ExtendedTimeLimit
	}
	return toSerialize, nil
}

type NullableStudentInformation struct {
	value *StudentInformation
	isSet bool
}

func (v NullableStudentInformation) Get() *StudentInformation {
	return v.value
}

func (v *NullableStudentInformation) Set(val *StudentInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableStudentInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableStudentInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStudentInformation(val *StudentInformation) *NullableStudentInformation {
	return &NullableStudentInformation{value: val, isSet: true}
}

func (v NullableStudentInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStudentInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


