/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the TaskProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskProgress{}

// TaskProgress struct for TaskProgress
type TaskProgress struct {
	// Task identification
	TaskId *string `json:"taskId,omitempty"`
	// Url to fetch progress
	TaskUri *string `json:"taskUri,omitempty"`
}

// NewTaskProgress instantiates a new TaskProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskProgress() *TaskProgress {
	this := TaskProgress{}
	return &this
}

// NewTaskProgressWithDefaults instantiates a new TaskProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskProgressWithDefaults() *TaskProgress {
	this := TaskProgress{}
	return &this
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *TaskProgress) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskProgress) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *TaskProgress) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *TaskProgress) SetTaskId(v string) {
	o.TaskId = &v
}

// GetTaskUri returns the TaskUri field value if set, zero value otherwise.
func (o *TaskProgress) GetTaskUri() string {
	if o == nil || IsNil(o.TaskUri) {
		var ret string
		return ret
	}
	return *o.TaskUri
}

// GetTaskUriOk returns a tuple with the TaskUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskProgress) GetTaskUriOk() (*string, bool) {
	if o == nil || IsNil(o.TaskUri) {
		return nil, false
	}
	return o.TaskUri, true
}

// HasTaskUri returns a boolean if a field has been set.
func (o *TaskProgress) HasTaskUri() bool {
	if o != nil && !IsNil(o.TaskUri) {
		return true
	}

	return false
}

// SetTaskUri gets a reference to the given string and assigns it to the TaskUri field.
func (o *TaskProgress) SetTaskUri(v string) {
	o.TaskUri = &v
}

func (o TaskProgress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TaskId) {
		toSerialize["taskId"] = o.TaskId
	}
	if !IsNil(o.TaskUri) {
		toSerialize["taskUri"] = o.TaskUri
	}
	return toSerialize, nil
}

type NullableTaskProgress struct {
	value *TaskProgress
	isSet bool
}

func (v NullableTaskProgress) Get() *TaskProgress {
	return v.value
}

func (v *NullableTaskProgress) Set(val *TaskProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskProgress(val *TaskProgress) *NullableTaskProgress {
	return &NullableTaskProgress{value: val, isSet: true}
}

func (v NullableTaskProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


