/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the CreateAssignmentSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAssignmentSettings{}

// CreateAssignmentSettings struct for CreateAssignmentSettings
type CreateAssignmentSettings struct {
	// Name of the assignment
	Name *string `json:"name,omitempty"`
	// Description of the assignment
	Description *string `json:"description,omitempty"`
	// GigaBox slot for the assignment
	GigaboxSlot *GigaBoxSlot `json:"gigaboxSlot,omitempty"`
}

// NewCreateAssignmentSettings instantiates a new CreateAssignmentSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAssignmentSettings() *CreateAssignmentSettings {
	this := CreateAssignmentSettings{}
	return &this
}

// NewCreateAssignmentSettingsWithDefaults instantiates a new CreateAssignmentSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAssignmentSettingsWithDefaults() *CreateAssignmentSettings {
	this := CreateAssignmentSettings{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateAssignmentSettings) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAssignmentSettings) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateAssignmentSettings) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateAssignmentSettings) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateAssignmentSettings) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAssignmentSettings) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateAssignmentSettings) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateAssignmentSettings) SetDescription(v string) {
	o.Description = &v
}

// GetGigaboxSlot returns the GigaboxSlot field value if set, zero value otherwise.
func (o *CreateAssignmentSettings) GetGigaboxSlot() GigaBoxSlot {
	if o == nil || IsNil(o.GigaboxSlot) {
		var ret GigaBoxSlot
		return ret
	}
	return *o.GigaboxSlot
}

// GetGigaboxSlotOk returns a tuple with the GigaboxSlot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAssignmentSettings) GetGigaboxSlotOk() (*GigaBoxSlot, bool) {
	if o == nil || IsNil(o.GigaboxSlot) {
		return nil, false
	}
	return o.GigaboxSlot, true
}

// HasGigaboxSlot returns a boolean if a field has been set.
func (o *CreateAssignmentSettings) HasGigaboxSlot() bool {
	if o != nil && !IsNil(o.GigaboxSlot) {
		return true
	}

	return false
}

// SetGigaboxSlot gets a reference to the given GigaBoxSlot and assigns it to the GigaboxSlot field.
func (o *CreateAssignmentSettings) SetGigaboxSlot(v GigaBoxSlot) {
	o.GigaboxSlot = &v
}

func (o CreateAssignmentSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAssignmentSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.GigaboxSlot) {
		toSerialize["gigaboxSlot"] = o.GigaboxSlot
	}
	return toSerialize, nil
}

type NullableCreateAssignmentSettings struct {
	value *CreateAssignmentSettings
	isSet bool
}

func (v NullableCreateAssignmentSettings) Get() *CreateAssignmentSettings {
	return v.value
}

func (v *NullableCreateAssignmentSettings) Set(val *CreateAssignmentSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAssignmentSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAssignmentSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAssignmentSettings(val *CreateAssignmentSettings) *NullableCreateAssignmentSettings {
	return &NullableCreateAssignmentSettings{value: val, isSet: true}
}

func (v NullableCreateAssignmentSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAssignmentSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


