/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the StackVersionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StackVersionInfo{}

// StackVersionInfo struct for StackVersionInfo
type StackVersionInfo struct {
	Id *string `json:"id,omitempty"`
	Changelog *string `json:"changelog,omitempty"`
	// ISO Date String
	Date *string `json:"date,omitempty"`
}

// NewStackVersionInfo instantiates a new StackVersionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackVersionInfo() *StackVersionInfo {
	this := StackVersionInfo{}
	return &this
}

// NewStackVersionInfoWithDefaults instantiates a new StackVersionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackVersionInfoWithDefaults() *StackVersionInfo {
	this := StackVersionInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StackVersionInfo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackVersionInfo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StackVersionInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *StackVersionInfo) SetId(v string) {
	o.Id = &v
}

// GetChangelog returns the Changelog field value if set, zero value otherwise.
func (o *StackVersionInfo) GetChangelog() string {
	if o == nil || IsNil(o.Changelog) {
		var ret string
		return ret
	}
	return *o.Changelog
}

// GetChangelogOk returns a tuple with the Changelog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackVersionInfo) GetChangelogOk() (*string, bool) {
	if o == nil || IsNil(o.Changelog) {
		return nil, false
	}
	return o.Changelog, true
}

// HasChangelog returns a boolean if a field has been set.
func (o *StackVersionInfo) HasChangelog() bool {
	if o != nil && !IsNil(o.Changelog) {
		return true
	}

	return false
}

// SetChangelog gets a reference to the given string and assigns it to the Changelog field.
func (o *StackVersionInfo) SetChangelog(v string) {
	o.Changelog = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *StackVersionInfo) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackVersionInfo) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *StackVersionInfo) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *StackVersionInfo) SetDate(v string) {
	o.Date = &v
}

func (o StackVersionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StackVersionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Changelog) {
		toSerialize["changelog"] = o.Changelog
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	return toSerialize, nil
}

type NullableStackVersionInfo struct {
	value *StackVersionInfo
	isSet bool
}

func (v NullableStackVersionInfo) Get() *StackVersionInfo {
	return v.value
}

func (v *NullableStackVersionInfo) Set(val *StackVersionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableStackVersionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableStackVersionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackVersionInfo(val *StackVersionInfo) *NullableStackVersionInfo {
	return &NullableStackVersionInfo{value: val, isSet: true}
}

func (v NullableStackVersionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackVersionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


