/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the CreateCourseModule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCourseModule{}

// CreateCourseModule struct for CreateCourseModule
type CreateCourseModule struct {
	// Name of the course module
	Name *string `json:"name,omitempty"`
}

// NewCreateCourseModule instantiates a new CreateCourseModule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCourseModule() *CreateCourseModule {
	this := CreateCourseModule{}
	return &this
}

// NewCreateCourseModuleWithDefaults instantiates a new CreateCourseModule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCourseModuleWithDefaults() *CreateCourseModule {
	this := CreateCourseModule{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateCourseModule) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCourseModule) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateCourseModule) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateCourseModule) SetName(v string) {
	o.Name = &v
}

func (o CreateCourseModule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCourseModule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCreateCourseModule struct {
	value *CreateCourseModule
	isSet bool
}

func (v NullableCreateCourseModule) Get() *CreateCourseModule {
	return v.value
}

func (v *NullableCreateCourseModule) Set(val *CreateCourseModule) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCourseModule) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCourseModule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCourseModule(val *CreateCourseModule) *NullableCreateCourseModule {
	return &NullableCreateCourseModule{value: val, isSet: true}
}

func (v NullableCreateCourseModule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCourseModule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


