/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the CreateAssignment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAssignment{}

// CreateAssignment struct for CreateAssignment
type CreateAssignment struct {
	// Module identifier
	ModuleId *string `json:"moduleId,omitempty"`
	// Settings for the assignment
	Settings *CreateAssignmentSettings `json:"settings,omitempty"`
}

// NewCreateAssignment instantiates a new CreateAssignment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAssignment() *CreateAssignment {
	this := CreateAssignment{}
	return &this
}

// NewCreateAssignmentWithDefaults instantiates a new CreateAssignment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAssignmentWithDefaults() *CreateAssignment {
	this := CreateAssignment{}
	return &this
}

// GetModuleId returns the ModuleId field value if set, zero value otherwise.
func (o *CreateAssignment) GetModuleId() string {
	if o == nil || IsNil(o.ModuleId) {
		var ret string
		return ret
	}
	return *o.ModuleId
}

// GetModuleIdOk returns a tuple with the ModuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAssignment) GetModuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.ModuleId) {
		return nil, false
	}
	return o.ModuleId, true
}

// HasModuleId returns a boolean if a field has been set.
func (o *CreateAssignment) HasModuleId() bool {
	if o != nil && !IsNil(o.ModuleId) {
		return true
	}

	return false
}

// SetModuleId gets a reference to the given string and assigns it to the ModuleId field.
func (o *CreateAssignment) SetModuleId(v string) {
	o.ModuleId = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *CreateAssignment) GetSettings() CreateAssignmentSettings {
	if o == nil || IsNil(o.Settings) {
		var ret CreateAssignmentSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAssignment) GetSettingsOk() (*CreateAssignmentSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *CreateAssignment) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given CreateAssignmentSettings and assigns it to the Settings field.
func (o *CreateAssignment) SetSettings(v CreateAssignmentSettings) {
	o.Settings = &v
}

func (o CreateAssignment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAssignment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ModuleId) {
		toSerialize["moduleId"] = o.ModuleId
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	return toSerialize, nil
}

type NullableCreateAssignment struct {
	value *CreateAssignment
	isSet bool
}

func (v NullableCreateAssignment) Get() *CreateAssignment {
	return v.value
}

func (v *NullableCreateAssignment) Set(val *CreateAssignment) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAssignment) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAssignment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAssignment(val *CreateAssignment) *NullableCreateAssignment {
	return &NullableCreateAssignment{value: val, isSet: true}
}

func (v NullableCreateAssignment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAssignment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


