/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the CreateAssignmentAnswer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAssignmentAnswer{}

// CreateAssignmentAnswer struct for CreateAssignmentAnswer
type CreateAssignmentAnswer struct {
	Id *string `json:"id,omitempty"`
}

// NewCreateAssignmentAnswer instantiates a new CreateAssignmentAnswer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAssignmentAnswer() *CreateAssignmentAnswer {
	this := CreateAssignmentAnswer{}
	return &this
}

// NewCreateAssignmentAnswerWithDefaults instantiates a new CreateAssignmentAnswer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAssignmentAnswerWithDefaults() *CreateAssignmentAnswer {
	this := CreateAssignmentAnswer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateAssignmentAnswer) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAssignmentAnswer) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateAssignmentAnswer) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateAssignmentAnswer) SetId(v string) {
	o.Id = &v
}

func (o CreateAssignmentAnswer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAssignmentAnswer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableCreateAssignmentAnswer struct {
	value *CreateAssignmentAnswer
	isSet bool
}

func (v NullableCreateAssignmentAnswer) Get() *CreateAssignmentAnswer {
	return v.value
}

func (v *NullableCreateAssignmentAnswer) Set(val *CreateAssignmentAnswer) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAssignmentAnswer) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAssignmentAnswer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAssignmentAnswer(val *CreateAssignmentAnswer) *NullableCreateAssignmentAnswer {
	return &NullableCreateAssignmentAnswer{value: val, isSet: true}
}

func (v NullableCreateAssignmentAnswer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAssignmentAnswer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


