/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the ArchiveCourse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArchiveCourse{}

// ArchiveCourse struct for ArchiveCourse
type ArchiveCourse struct {
	// Course archive date, ISO Date String
	ArchivedDate *string `json:"archivedDate,omitempty"`
}

// NewArchiveCourse instantiates a new ArchiveCourse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArchiveCourse() *ArchiveCourse {
	this := ArchiveCourse{}
	return &this
}

// NewArchiveCourseWithDefaults instantiates a new ArchiveCourse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArchiveCourseWithDefaults() *ArchiveCourse {
	this := ArchiveCourse{}
	return &this
}

// GetArchivedDate returns the ArchivedDate field value if set, zero value otherwise.
func (o *ArchiveCourse) GetArchivedDate() string {
	if o == nil || IsNil(o.ArchivedDate) {
		var ret string
		return ret
	}
	return *o.ArchivedDate
}

// GetArchivedDateOk returns a tuple with the ArchivedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArchiveCourse) GetArchivedDateOk() (*string, bool) {
	if o == nil || IsNil(o.ArchivedDate) {
		return nil, false
	}
	return o.ArchivedDate, true
}

// HasArchivedDate returns a boolean if a field has been set.
func (o *ArchiveCourse) HasArchivedDate() bool {
	if o != nil && !IsNil(o.ArchivedDate) {
		return true
	}

	return false
}

// SetArchivedDate gets a reference to the given string and assigns it to the ArchivedDate field.
func (o *ArchiveCourse) SetArchivedDate(v string) {
	o.ArchivedDate = &v
}

func (o ArchiveCourse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArchiveCourse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ArchivedDate) {
		toSerialize["archivedDate"] = o.ArchivedDate
	}
	return toSerialize, nil
}

type NullableArchiveCourse struct {
	value *ArchiveCourse
	isSet bool
}

func (v NullableArchiveCourse) Get() *ArchiveCourse {
	return v.value
}

func (v *NullableArchiveCourse) Set(val *ArchiveCourse) {
	v.value = val
	v.isSet = true
}

func (v NullableArchiveCourse) IsSet() bool {
	return v.isSet
}

func (v *NullableArchiveCourse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArchiveCourse(val *ArchiveCourse) *NullableArchiveCourse {
	return &NullableArchiveCourse{value: val, isSet: true}
}

func (v NullableArchiveCourse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArchiveCourse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


