/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the FilterLearnersForMentorsAnswerExample type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilterLearnersForMentorsAnswerExample{}

// FilterLearnersForMentorsAnswerExample struct for FilterLearnersForMentorsAnswerExample
type FilterLearnersForMentorsAnswerExample struct {
	Completed *bool `json:"completed,omitempty"`
}

// NewFilterLearnersForMentorsAnswerExample instantiates a new FilterLearnersForMentorsAnswerExample object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterLearnersForMentorsAnswerExample() *FilterLearnersForMentorsAnswerExample {
	this := FilterLearnersForMentorsAnswerExample{}
	return &this
}

// NewFilterLearnersForMentorsAnswerExampleWithDefaults instantiates a new FilterLearnersForMentorsAnswerExample object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterLearnersForMentorsAnswerExampleWithDefaults() *FilterLearnersForMentorsAnswerExample {
	this := FilterLearnersForMentorsAnswerExample{}
	return &this
}

// GetCompleted returns the Completed field value if set, zero value otherwise.
func (o *FilterLearnersForMentorsAnswerExample) GetCompleted() bool {
	if o == nil || IsNil(o.Completed) {
		var ret bool
		return ret
	}
	return *o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterLearnersForMentorsAnswerExample) GetCompletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Completed) {
		return nil, false
	}
	return o.Completed, true
}

// HasCompleted returns a boolean if a field has been set.
func (o *FilterLearnersForMentorsAnswerExample) HasCompleted() bool {
	if o != nil && !IsNil(o.Completed) {
		return true
	}

	return false
}

// SetCompleted gets a reference to the given bool and assigns it to the Completed field.
func (o *FilterLearnersForMentorsAnswerExample) SetCompleted(v bool) {
	o.Completed = &v
}

func (o FilterLearnersForMentorsAnswerExample) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilterLearnersForMentorsAnswerExample) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Completed) {
		toSerialize["completed"] = o.Completed
	}
	return toSerialize, nil
}

type NullableFilterLearnersForMentorsAnswerExample struct {
	value *FilterLearnersForMentorsAnswerExample
	isSet bool
}

func (v NullableFilterLearnersForMentorsAnswerExample) Get() *FilterLearnersForMentorsAnswerExample {
	return v.value
}

func (v *NullableFilterLearnersForMentorsAnswerExample) Set(val *FilterLearnersForMentorsAnswerExample) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterLearnersForMentorsAnswerExample) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterLearnersForMentorsAnswerExample) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterLearnersForMentorsAnswerExample(val *FilterLearnersForMentorsAnswerExample) *NullableFilterLearnersForMentorsAnswerExample {
	return &NullableFilterLearnersForMentorsAnswerExample{value: val, isSet: true}
}

func (v NullableFilterLearnersForMentorsAnswerExample) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterLearnersForMentorsAnswerExample) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


