/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the EventsList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventsList{}

// EventsList struct for EventsList
type EventsList struct {
	// Event data
	Events []Event `json:"events,omitempty"`
	// Continuation request token
	NextToken *string `json:"nextToken,omitempty"`
}

// NewEventsList instantiates a new EventsList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventsList() *EventsList {
	this := EventsList{}
	return &this
}

// NewEventsListWithDefaults instantiates a new EventsList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventsListWithDefaults() *EventsList {
	this := EventsList{}
	return &this
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *EventsList) GetEvents() []Event {
	if o == nil || IsNil(o.Events) {
		var ret []Event
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsList) GetEventsOk() ([]Event, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *EventsList) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []Event and assigns it to the Events field.
func (o *EventsList) SetEvents(v []Event) {
	o.Events = v
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *EventsList) GetNextToken() string {
	if o == nil || IsNil(o.NextToken) {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsList) GetNextTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextToken) {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *EventsList) HasNextToken() bool {
	if o != nil && !IsNil(o.NextToken) {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *EventsList) SetNextToken(v string) {
	o.NextToken = &v
}

func (o EventsList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventsList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.NextToken) {
		toSerialize["nextToken"] = o.NextToken
	}
	return toSerialize, nil
}

type NullableEventsList struct {
	value *EventsList
	isSet bool
}

func (v NullableEventsList) Get() *EventsList {
	return v.value
}

func (v *NullableEventsList) Set(val *EventsList) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsList) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsList(val *EventsList) *NullableEventsList {
	return &NullableEventsList{value: val, isSet: true}
}

func (v NullableEventsList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


