/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the CreateCourseAnswer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCourseAnswer{}

// CreateCourseAnswer struct for CreateCourseAnswer
type CreateCourseAnswer struct {
	Id *string `json:"id,omitempty"`
}

// NewCreateCourseAnswer instantiates a new CreateCourseAnswer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCourseAnswer() *CreateCourseAnswer {
	this := CreateCourseAnswer{}
	return &this
}

// NewCreateCourseAnswerWithDefaults instantiates a new CreateCourseAnswer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCourseAnswerWithDefaults() *CreateCourseAnswer {
	this := CreateCourseAnswer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateCourseAnswer) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCourseAnswer) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateCourseAnswer) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateCourseAnswer) SetId(v string) {
	o.Id = &v
}

func (o CreateCourseAnswer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCourseAnswer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableCreateCourseAnswer struct {
	value *CreateCourseAnswer
	isSet bool
}

func (v NullableCreateCourseAnswer) Get() *CreateCourseAnswer {
	return v.value
}

func (v *NullableCreateCourseAnswer) Set(val *CreateCourseAnswer) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCourseAnswer) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCourseAnswer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCourseAnswer(val *CreateCourseAnswer) *NullableCreateCourseAnswer {
	return &NullableCreateCourseAnswer{value: val, isSet: true}
}

func (v NullableCreateCourseAnswer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCourseAnswer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


