/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the DownloadStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DownloadStatus{}

// DownloadStatus struct for DownloadStatus
type DownloadStatus struct {
	// Task identification
	TaskId *string `json:"taskId,omitempty"`
	// Task status
	Done *bool `json:"done,omitempty"`
	// If task completed - url for download
	Url *string `json:"url,omitempty"`
	// Error description if task failed
	Error *string `json:"error,omitempty"`
}

// NewDownloadStatus instantiates a new DownloadStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDownloadStatus() *DownloadStatus {
	this := DownloadStatus{}
	return &this
}

// NewDownloadStatusWithDefaults instantiates a new DownloadStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDownloadStatusWithDefaults() *DownloadStatus {
	this := DownloadStatus{}
	return &this
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *DownloadStatus) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadStatus) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *DownloadStatus) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *DownloadStatus) SetTaskId(v string) {
	o.TaskId = &v
}

// GetDone returns the Done field value if set, zero value otherwise.
func (o *DownloadStatus) GetDone() bool {
	if o == nil || IsNil(o.Done) {
		var ret bool
		return ret
	}
	return *o.Done
}

// GetDoneOk returns a tuple with the Done field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadStatus) GetDoneOk() (*bool, bool) {
	if o == nil || IsNil(o.Done) {
		return nil, false
	}
	return o.Done, true
}

// HasDone returns a boolean if a field has been set.
func (o *DownloadStatus) HasDone() bool {
	if o != nil && !IsNil(o.Done) {
		return true
	}

	return false
}

// SetDone gets a reference to the given bool and assigns it to the Done field.
func (o *DownloadStatus) SetDone(v bool) {
	o.Done = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *DownloadStatus) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadStatus) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *DownloadStatus) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *DownloadStatus) SetUrl(v string) {
	o.Url = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *DownloadStatus) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadStatus) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *DownloadStatus) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *DownloadStatus) SetError(v string) {
	o.Error = &v
}

func (o DownloadStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DownloadStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TaskId) {
		toSerialize["taskId"] = o.TaskId
	}
	if !IsNil(o.Done) {
		toSerialize["done"] = o.Done
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableDownloadStatus struct {
	value *DownloadStatus
	isSet bool
}

func (v NullableDownloadStatus) Get() *DownloadStatus {
	return v.value
}

func (v *NullableDownloadStatus) Set(val *DownloadStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDownloadStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDownloadStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDownloadStatus(val *DownloadStatus) *NullableDownloadStatus {
	return &NullableDownloadStatus{value: val, isSet: true}
}

func (v NullableDownloadStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDownloadStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


