/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the AssignmentSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignmentSettings{}

// AssignmentSettings struct for AssignmentSettings
type AssignmentSettings struct {
	IsDisabled *bool `json:"isDisabled,omitempty"`
	ReleaseGrades *bool `json:"releaseGrades,omitempty"`
	EnableResetAssignmentByStudent *bool `json:"enableResetAssignmentByStudent,omitempty"`
	DisableDownloadByStudent *bool `json:"disableDownloadByStudent,omitempty"`
	// Assignment visibility
	VisibilityOnDisabled *string `json:"visibilityOnDisabled,omitempty"`
	// Assignment visibility on completed
	VisibilityOnCompleted *string `json:"visibilityOnCompleted,omitempty"`
	PenaltiesV2 *PenaltySettings `json:"penaltiesV2,omitempty"`
	ExamMode *ExamMode `json:"examMode,omitempty"`
	Start *string `json:"start,omitempty"`
	Due *string `json:"due,omitempty"`
	MarkAsCompleteOnDueDate *bool `json:"markAsCompleteOnDueDate,omitempty"`
	End *string `json:"end,omitempty"`
	// Assignment action on completed
	Action *string `json:"action,omitempty"`
}

// NewAssignmentSettings instantiates a new AssignmentSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignmentSettings() *AssignmentSettings {
	this := AssignmentSettings{}
	return &this
}

// NewAssignmentSettingsWithDefaults instantiates a new AssignmentSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignmentSettingsWithDefaults() *AssignmentSettings {
	this := AssignmentSettings{}
	return &this
}

// GetIsDisabled returns the IsDisabled field value if set, zero value otherwise.
func (o *AssignmentSettings) GetIsDisabled() bool {
	if o == nil || IsNil(o.IsDisabled) {
		var ret bool
		return ret
	}
	return *o.IsDisabled
}

// GetIsDisabledOk returns a tuple with the IsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetIsDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDisabled) {
		return nil, false
	}
	return o.IsDisabled, true
}

// HasIsDisabled returns a boolean if a field has been set.
func (o *AssignmentSettings) HasIsDisabled() bool {
	if o != nil && !IsNil(o.IsDisabled) {
		return true
	}

	return false
}

// SetIsDisabled gets a reference to the given bool and assigns it to the IsDisabled field.
func (o *AssignmentSettings) SetIsDisabled(v bool) {
	o.IsDisabled = &v
}

// GetReleaseGrades returns the ReleaseGrades field value if set, zero value otherwise.
func (o *AssignmentSettings) GetReleaseGrades() bool {
	if o == nil || IsNil(o.ReleaseGrades) {
		var ret bool
		return ret
	}
	return *o.ReleaseGrades
}

// GetReleaseGradesOk returns a tuple with the ReleaseGrades field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetReleaseGradesOk() (*bool, bool) {
	if o == nil || IsNil(o.ReleaseGrades) {
		return nil, false
	}
	return o.ReleaseGrades, true
}

// HasReleaseGrades returns a boolean if a field has been set.
func (o *AssignmentSettings) HasReleaseGrades() bool {
	if o != nil && !IsNil(o.ReleaseGrades) {
		return true
	}

	return false
}

// SetReleaseGrades gets a reference to the given bool and assigns it to the ReleaseGrades field.
func (o *AssignmentSettings) SetReleaseGrades(v bool) {
	o.ReleaseGrades = &v
}

// GetEnableResetAssignmentByStudent returns the EnableResetAssignmentByStudent field value if set, zero value otherwise.
func (o *AssignmentSettings) GetEnableResetAssignmentByStudent() bool {
	if o == nil || IsNil(o.EnableResetAssignmentByStudent) {
		var ret bool
		return ret
	}
	return *o.EnableResetAssignmentByStudent
}

// GetEnableResetAssignmentByStudentOk returns a tuple with the EnableResetAssignmentByStudent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetEnableResetAssignmentByStudentOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableResetAssignmentByStudent) {
		return nil, false
	}
	return o.EnableResetAssignmentByStudent, true
}

// HasEnableResetAssignmentByStudent returns a boolean if a field has been set.
func (o *AssignmentSettings) HasEnableResetAssignmentByStudent() bool {
	if o != nil && !IsNil(o.EnableResetAssignmentByStudent) {
		return true
	}

	return false
}

// SetEnableResetAssignmentByStudent gets a reference to the given bool and assigns it to the EnableResetAssignmentByStudent field.
func (o *AssignmentSettings) SetEnableResetAssignmentByStudent(v bool) {
	o.EnableResetAssignmentByStudent = &v
}

// GetDisableDownloadByStudent returns the DisableDownloadByStudent field value if set, zero value otherwise.
func (o *AssignmentSettings) GetDisableDownloadByStudent() bool {
	if o == nil || IsNil(o.DisableDownloadByStudent) {
		var ret bool
		return ret
	}
	return *o.DisableDownloadByStudent
}

// GetDisableDownloadByStudentOk returns a tuple with the DisableDownloadByStudent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetDisableDownloadByStudentOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableDownloadByStudent) {
		return nil, false
	}
	return o.DisableDownloadByStudent, true
}

// HasDisableDownloadByStudent returns a boolean if a field has been set.
func (o *AssignmentSettings) HasDisableDownloadByStudent() bool {
	if o != nil && !IsNil(o.DisableDownloadByStudent) {
		return true
	}

	return false
}

// SetDisableDownloadByStudent gets a reference to the given bool and assigns it to the DisableDownloadByStudent field.
func (o *AssignmentSettings) SetDisableDownloadByStudent(v bool) {
	o.DisableDownloadByStudent = &v
}

// GetVisibilityOnDisabled returns the VisibilityOnDisabled field value if set, zero value otherwise.
func (o *AssignmentSettings) GetVisibilityOnDisabled() string {
	if o == nil || IsNil(o.VisibilityOnDisabled) {
		var ret string
		return ret
	}
	return *o.VisibilityOnDisabled
}

// GetVisibilityOnDisabledOk returns a tuple with the VisibilityOnDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetVisibilityOnDisabledOk() (*string, bool) {
	if o == nil || IsNil(o.VisibilityOnDisabled) {
		return nil, false
	}
	return o.VisibilityOnDisabled, true
}

// HasVisibilityOnDisabled returns a boolean if a field has been set.
func (o *AssignmentSettings) HasVisibilityOnDisabled() bool {
	if o != nil && !IsNil(o.VisibilityOnDisabled) {
		return true
	}

	return false
}

// SetVisibilityOnDisabled gets a reference to the given string and assigns it to the VisibilityOnDisabled field.
func (o *AssignmentSettings) SetVisibilityOnDisabled(v string) {
	o.VisibilityOnDisabled = &v
}

// GetVisibilityOnCompleted returns the VisibilityOnCompleted field value if set, zero value otherwise.
func (o *AssignmentSettings) GetVisibilityOnCompleted() string {
	if o == nil || IsNil(o.VisibilityOnCompleted) {
		var ret string
		return ret
	}
	return *o.VisibilityOnCompleted
}

// GetVisibilityOnCompletedOk returns a tuple with the VisibilityOnCompleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetVisibilityOnCompletedOk() (*string, bool) {
	if o == nil || IsNil(o.VisibilityOnCompleted) {
		return nil, false
	}
	return o.VisibilityOnCompleted, true
}

// HasVisibilityOnCompleted returns a boolean if a field has been set.
func (o *AssignmentSettings) HasVisibilityOnCompleted() bool {
	if o != nil && !IsNil(o.VisibilityOnCompleted) {
		return true
	}

	return false
}

// SetVisibilityOnCompleted gets a reference to the given string and assigns it to the VisibilityOnCompleted field.
func (o *AssignmentSettings) SetVisibilityOnCompleted(v string) {
	o.VisibilityOnCompleted = &v
}

// GetPenaltiesV2 returns the PenaltiesV2 field value if set, zero value otherwise.
func (o *AssignmentSettings) GetPenaltiesV2() PenaltySettings {
	if o == nil || IsNil(o.PenaltiesV2) {
		var ret PenaltySettings
		return ret
	}
	return *o.PenaltiesV2
}

// GetPenaltiesV2Ok returns a tuple with the PenaltiesV2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetPenaltiesV2Ok() (*PenaltySettings, bool) {
	if o == nil || IsNil(o.PenaltiesV2) {
		return nil, false
	}
	return o.PenaltiesV2, true
}

// HasPenaltiesV2 returns a boolean if a field has been set.
func (o *AssignmentSettings) HasPenaltiesV2() bool {
	if o != nil && !IsNil(o.PenaltiesV2) {
		return true
	}

	return false
}

// SetPenaltiesV2 gets a reference to the given PenaltySettings and assigns it to the PenaltiesV2 field.
func (o *AssignmentSettings) SetPenaltiesV2(v PenaltySettings) {
	o.PenaltiesV2 = &v
}

// GetExamMode returns the ExamMode field value if set, zero value otherwise.
func (o *AssignmentSettings) GetExamMode() ExamMode {
	if o == nil || IsNil(o.ExamMode) {
		var ret ExamMode
		return ret
	}
	return *o.ExamMode
}

// GetExamModeOk returns a tuple with the ExamMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetExamModeOk() (*ExamMode, bool) {
	if o == nil || IsNil(o.ExamMode) {
		return nil, false
	}
	return o.ExamMode, true
}

// HasExamMode returns a boolean if a field has been set.
func (o *AssignmentSettings) HasExamMode() bool {
	if o != nil && !IsNil(o.ExamMode) {
		return true
	}

	return false
}

// SetExamMode gets a reference to the given ExamMode and assigns it to the ExamMode field.
func (o *AssignmentSettings) SetExamMode(v ExamMode) {
	o.ExamMode = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *AssignmentSettings) GetStart() string {
	if o == nil || IsNil(o.Start) {
		var ret string
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetStartOk() (*string, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *AssignmentSettings) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given string and assigns it to the Start field.
func (o *AssignmentSettings) SetStart(v string) {
	o.Start = &v
}

// GetDue returns the Due field value if set, zero value otherwise.
func (o *AssignmentSettings) GetDue() string {
	if o == nil || IsNil(o.Due) {
		var ret string
		return ret
	}
	return *o.Due
}

// GetDueOk returns a tuple with the Due field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetDueOk() (*string, bool) {
	if o == nil || IsNil(o.Due) {
		return nil, false
	}
	return o.Due, true
}

// HasDue returns a boolean if a field has been set.
func (o *AssignmentSettings) HasDue() bool {
	if o != nil && !IsNil(o.Due) {
		return true
	}

	return false
}

// SetDue gets a reference to the given string and assigns it to the Due field.
func (o *AssignmentSettings) SetDue(v string) {
	o.Due = &v
}

// GetMarkAsCompleteOnDueDate returns the MarkAsCompleteOnDueDate field value if set, zero value otherwise.
func (o *AssignmentSettings) GetMarkAsCompleteOnDueDate() bool {
	if o == nil || IsNil(o.MarkAsCompleteOnDueDate) {
		var ret bool
		return ret
	}
	return *o.MarkAsCompleteOnDueDate
}

// GetMarkAsCompleteOnDueDateOk returns a tuple with the MarkAsCompleteOnDueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetMarkAsCompleteOnDueDateOk() (*bool, bool) {
	if o == nil || IsNil(o.MarkAsCompleteOnDueDate) {
		return nil, false
	}
	return o.MarkAsCompleteOnDueDate, true
}

// HasMarkAsCompleteOnDueDate returns a boolean if a field has been set.
func (o *AssignmentSettings) HasMarkAsCompleteOnDueDate() bool {
	if o != nil && !IsNil(o.MarkAsCompleteOnDueDate) {
		return true
	}

	return false
}

// SetMarkAsCompleteOnDueDate gets a reference to the given bool and assigns it to the MarkAsCompleteOnDueDate field.
func (o *AssignmentSettings) SetMarkAsCompleteOnDueDate(v bool) {
	o.MarkAsCompleteOnDueDate = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *AssignmentSettings) GetEnd() string {
	if o == nil || IsNil(o.End) {
		var ret string
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetEndOk() (*string, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *AssignmentSettings) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given string and assigns it to the End field.
func (o *AssignmentSettings) SetEnd(v string) {
	o.End = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *AssignmentSettings) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentSettings) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *AssignmentSettings) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *AssignmentSettings) SetAction(v string) {
	o.Action = &v
}

func (o AssignmentSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignmentSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsDisabled) {
		toSerialize["isDisabled"] = o.IsDisabled
	}
	if !IsNil(o.ReleaseGrades) {
		toSerialize["releaseGrades"] = o.ReleaseGrades
	}
	if !IsNil(o.EnableResetAssignmentByStudent) {
		toSerialize["enableResetAssignmentByStudent"] = o.EnableResetAssignmentByStudent
	}
	if !IsNil(o.DisableDownloadByStudent) {
		toSerialize["disableDownloadByStudent"] = o.DisableDownloadByStudent
	}
	if !IsNil(o.VisibilityOnDisabled) {
		toSerialize["visibilityOnDisabled"] = o.VisibilityOnDisabled
	}
	if !IsNil(o.VisibilityOnCompleted) {
		toSerialize["visibilityOnCompleted"] = o.VisibilityOnCompleted
	}
	if !IsNil(o.PenaltiesV2) {
		toSerialize["penaltiesV2"] = o.PenaltiesV2
	}
	if !IsNil(o.ExamMode) {
		toSerialize["examMode"] = o.ExamMode
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.Due) {
		toSerialize["due"] = o.Due
	}
	if !IsNil(o.MarkAsCompleteOnDueDate) {
		toSerialize["markAsCompleteOnDueDate"] = o.MarkAsCompleteOnDueDate
	}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	return toSerialize, nil
}

type NullableAssignmentSettings struct {
	value *AssignmentSettings
	isSet bool
}

func (v NullableAssignmentSettings) Get() *AssignmentSettings {
	return v.value
}

func (v *NullableAssignmentSettings) Set(val *AssignmentSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignmentSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignmentSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignmentSettings(val *AssignmentSettings) *NullableAssignmentSettings {
	return &NullableAssignmentSettings{value: val, isSet: true}
}

func (v NullableAssignmentSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignmentSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


