/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the AssignmentProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignmentProgress{}

// AssignmentProgress struct for AssignmentProgress
type AssignmentProgress struct {
	// Seconds spent in the assignment
	SecondsSpent *int32 `json:"seconds_spent,omitempty"`
	// Student grade
	Grade *int32 `json:"grade,omitempty"`
	// Assignment status
	Status *string `json:"status,omitempty"`
	// Assignment completion date, ISO Date String
	CompletionDate *string `json:"completion_date,omitempty"`
	// Extended time limit
	ExtendedTimeLimit *int32 `json:"extended_time_limit,omitempty"`
	// Extended deadline
	ExtendedDeadline *int32 `json:"extended_deadline,omitempty"`
}

// NewAssignmentProgress instantiates a new AssignmentProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignmentProgress() *AssignmentProgress {
	this := AssignmentProgress{}
	return &this
}

// NewAssignmentProgressWithDefaults instantiates a new AssignmentProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignmentProgressWithDefaults() *AssignmentProgress {
	this := AssignmentProgress{}
	return &this
}

// GetSecondsSpent returns the SecondsSpent field value if set, zero value otherwise.
func (o *AssignmentProgress) GetSecondsSpent() int32 {
	if o == nil || IsNil(o.SecondsSpent) {
		var ret int32
		return ret
	}
	return *o.SecondsSpent
}

// GetSecondsSpentOk returns a tuple with the SecondsSpent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentProgress) GetSecondsSpentOk() (*int32, bool) {
	if o == nil || IsNil(o.SecondsSpent) {
		return nil, false
	}
	return o.SecondsSpent, true
}

// HasSecondsSpent returns a boolean if a field has been set.
func (o *AssignmentProgress) HasSecondsSpent() bool {
	if o != nil && !IsNil(o.SecondsSpent) {
		return true
	}

	return false
}

// SetSecondsSpent gets a reference to the given int32 and assigns it to the SecondsSpent field.
func (o *AssignmentProgress) SetSecondsSpent(v int32) {
	o.SecondsSpent = &v
}

// GetGrade returns the Grade field value if set, zero value otherwise.
func (o *AssignmentProgress) GetGrade() int32 {
	if o == nil || IsNil(o.Grade) {
		var ret int32
		return ret
	}
	return *o.Grade
}

// GetGradeOk returns a tuple with the Grade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentProgress) GetGradeOk() (*int32, bool) {
	if o == nil || IsNil(o.Grade) {
		return nil, false
	}
	return o.Grade, true
}

// HasGrade returns a boolean if a field has been set.
func (o *AssignmentProgress) HasGrade() bool {
	if o != nil && !IsNil(o.Grade) {
		return true
	}

	return false
}

// SetGrade gets a reference to the given int32 and assigns it to the Grade field.
func (o *AssignmentProgress) SetGrade(v int32) {
	o.Grade = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AssignmentProgress) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentProgress) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AssignmentProgress) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AssignmentProgress) SetStatus(v string) {
	o.Status = &v
}

// GetCompletionDate returns the CompletionDate field value if set, zero value otherwise.
func (o *AssignmentProgress) GetCompletionDate() string {
	if o == nil || IsNil(o.CompletionDate) {
		var ret string
		return ret
	}
	return *o.CompletionDate
}

// GetCompletionDateOk returns a tuple with the CompletionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentProgress) GetCompletionDateOk() (*string, bool) {
	if o == nil || IsNil(o.CompletionDate) {
		return nil, false
	}
	return o.CompletionDate, true
}

// HasCompletionDate returns a boolean if a field has been set.
func (o *AssignmentProgress) HasCompletionDate() bool {
	if o != nil && !IsNil(o.CompletionDate) {
		return true
	}

	return false
}

// SetCompletionDate gets a reference to the given string and assigns it to the CompletionDate field.
func (o *AssignmentProgress) SetCompletionDate(v string) {
	o.CompletionDate = &v
}

// GetExtendedTimeLimit returns the ExtendedTimeLimit field value if set, zero value otherwise.
func (o *AssignmentProgress) GetExtendedTimeLimit() int32 {
	if o == nil || IsNil(o.ExtendedTimeLimit) {
		var ret int32
		return ret
	}
	return *o.ExtendedTimeLimit
}

// GetExtendedTimeLimitOk returns a tuple with the ExtendedTimeLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentProgress) GetExtendedTimeLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtendedTimeLimit) {
		return nil, false
	}
	return o.ExtendedTimeLimit, true
}

// HasExtendedTimeLimit returns a boolean if a field has been set.
func (o *AssignmentProgress) HasExtendedTimeLimit() bool {
	if o != nil && !IsNil(o.ExtendedTimeLimit) {
		return true
	}

	return false
}

// SetExtendedTimeLimit gets a reference to the given int32 and assigns it to the ExtendedTimeLimit field.
func (o *AssignmentProgress) SetExtendedTimeLimit(v int32) {
	o.ExtendedTimeLimit = &v
}

// GetExtendedDeadline returns the ExtendedDeadline field value if set, zero value otherwise.
func (o *AssignmentProgress) GetExtendedDeadline() int32 {
	if o == nil || IsNil(o.ExtendedDeadline) {
		var ret int32
		return ret
	}
	return *o.ExtendedDeadline
}

// GetExtendedDeadlineOk returns a tuple with the ExtendedDeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentProgress) GetExtendedDeadlineOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtendedDeadline) {
		return nil, false
	}
	return o.ExtendedDeadline, true
}

// HasExtendedDeadline returns a boolean if a field has been set.
func (o *AssignmentProgress) HasExtendedDeadline() bool {
	if o != nil && !IsNil(o.ExtendedDeadline) {
		return true
	}

	return false
}

// SetExtendedDeadline gets a reference to the given int32 and assigns it to the ExtendedDeadline field.
func (o *AssignmentProgress) SetExtendedDeadline(v int32) {
	o.ExtendedDeadline = &v
}

func (o AssignmentProgress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignmentProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SecondsSpent) {
		toSerialize["seconds_spent"] = o.SecondsSpent
	}
	if !IsNil(o.Grade) {
		toSerialize["grade"] = o.Grade
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CompletionDate) {
		toSerialize["completion_date"] = o.CompletionDate
	}
	if !IsNil(o.ExtendedTimeLimit) {
		toSerialize["extended_time_limit"] = o.ExtendedTimeLimit
	}
	if !IsNil(o.ExtendedDeadline) {
		toSerialize["extended_deadline"] = o.ExtendedDeadline
	}
	return toSerialize, nil
}

type NullableAssignmentProgress struct {
	value *AssignmentProgress
	isSet bool
}

func (v NullableAssignmentProgress) Get() *AssignmentProgress {
	return v.value
}

func (v *NullableAssignmentProgress) Set(val *AssignmentProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignmentProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignmentProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignmentProgress(val *AssignmentProgress) *NullableAssignmentProgress {
	return &NullableAssignmentProgress{value: val, isSet: true}
}

func (v NullableAssignmentProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignmentProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


