/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the AddTeacherToCourseAnswer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddTeacherToCourseAnswer{}

// AddTeacherToCourseAnswer struct for AddTeacherToCourseAnswer
type AddTeacherToCourseAnswer struct {
	Completed *bool `json:"completed,omitempty"`
}

// NewAddTeacherToCourseAnswer instantiates a new AddTeacherToCourseAnswer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTeacherToCourseAnswer() *AddTeacherToCourseAnswer {
	this := AddTeacherToCourseAnswer{}
	return &this
}

// NewAddTeacherToCourseAnswerWithDefaults instantiates a new AddTeacherToCourseAnswer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTeacherToCourseAnswerWithDefaults() *AddTeacherToCourseAnswer {
	this := AddTeacherToCourseAnswer{}
	return &this
}

// GetCompleted returns the Completed field value if set, zero value otherwise.
func (o *AddTeacherToCourseAnswer) GetCompleted() bool {
	if o == nil || IsNil(o.Completed) {
		var ret bool
		return ret
	}
	return *o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddTeacherToCourseAnswer) GetCompletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Completed) {
		return nil, false
	}
	return o.Completed, true
}

// HasCompleted returns a boolean if a field has been set.
func (o *AddTeacherToCourseAnswer) HasCompleted() bool {
	if o != nil && !IsNil(o.Completed) {
		return true
	}

	return false
}

// SetCompleted gets a reference to the given bool and assigns it to the Completed field.
func (o *AddTeacherToCourseAnswer) SetCompleted(v bool) {
	o.Completed = &v
}

func (o AddTeacherToCourseAnswer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddTeacherToCourseAnswer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Completed) {
		toSerialize["completed"] = o.Completed
	}
	return toSerialize, nil
}

type NullableAddTeacherToCourseAnswer struct {
	value *AddTeacherToCourseAnswer
	isSet bool
}

func (v NullableAddTeacherToCourseAnswer) Get() *AddTeacherToCourseAnswer {
	return v.value
}

func (v *NullableAddTeacherToCourseAnswer) Set(val *AddTeacherToCourseAnswer) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTeacherToCourseAnswer) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTeacherToCourseAnswer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTeacherToCourseAnswer(val *AddTeacherToCourseAnswer) *NullableAddTeacherToCourseAnswer {
	return &NullableAddTeacherToCourseAnswer{value: val, isSet: true}
}

func (v NullableAddTeacherToCourseAnswer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTeacherToCourseAnswer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


