/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the StackPublishInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StackPublishInfo{}

// StackPublishInfo struct for StackPublishInfo
type StackPublishInfo struct {
	Status *string `json:"status,omitempty"`
	Error *string `json:"error,omitempty"`
	ProvisionLog *string `json:"provision_log,omitempty"`
}

// NewStackPublishInfo instantiates a new StackPublishInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackPublishInfo() *StackPublishInfo {
	this := StackPublishInfo{}
	return &this
}

// NewStackPublishInfoWithDefaults instantiates a new StackPublishInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackPublishInfoWithDefaults() *StackPublishInfo {
	this := StackPublishInfo{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *StackPublishInfo) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackPublishInfo) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *StackPublishInfo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *StackPublishInfo) SetStatus(v string) {
	o.Status = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *StackPublishInfo) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackPublishInfo) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *StackPublishInfo) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *StackPublishInfo) SetError(v string) {
	o.Error = &v
}

// GetProvisionLog returns the ProvisionLog field value if set, zero value otherwise.
func (o *StackPublishInfo) GetProvisionLog() string {
	if o == nil || IsNil(o.ProvisionLog) {
		var ret string
		return ret
	}
	return *o.ProvisionLog
}

// GetProvisionLogOk returns a tuple with the ProvisionLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackPublishInfo) GetProvisionLogOk() (*string, bool) {
	if o == nil || IsNil(o.ProvisionLog) {
		return nil, false
	}
	return o.ProvisionLog, true
}

// HasProvisionLog returns a boolean if a field has been set.
func (o *StackPublishInfo) HasProvisionLog() bool {
	if o != nil && !IsNil(o.ProvisionLog) {
		return true
	}

	return false
}

// SetProvisionLog gets a reference to the given string and assigns it to the ProvisionLog field.
func (o *StackPublishInfo) SetProvisionLog(v string) {
	o.ProvisionLog = &v
}

func (o StackPublishInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StackPublishInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.ProvisionLog) {
		toSerialize["provision_log"] = o.ProvisionLog
	}
	return toSerialize, nil
}

type NullableStackPublishInfo struct {
	value *StackPublishInfo
	isSet bool
}

func (v NullableStackPublishInfo) Get() *StackPublishInfo {
	return v.value
}

func (v *NullableStackPublishInfo) Set(val *StackPublishInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableStackPublishInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableStackPublishInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackPublishInfo(val *StackPublishInfo) *NullableStackPublishInfo {
	return &NullableStackPublishInfo{value: val, isSet: true}
}

func (v NullableStackPublishInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackPublishInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


