/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the CreateCourseModuleAnswer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCourseModuleAnswer{}

// CreateCourseModuleAnswer struct for CreateCourseModuleAnswer
type CreateCourseModuleAnswer struct {
	Id *string `json:"id,omitempty"`
}

// NewCreateCourseModuleAnswer instantiates a new CreateCourseModuleAnswer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCourseModuleAnswer() *CreateCourseModuleAnswer {
	this := CreateCourseModuleAnswer{}
	return &this
}

// NewCreateCourseModuleAnswerWithDefaults instantiates a new CreateCourseModuleAnswer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCourseModuleAnswerWithDefaults() *CreateCourseModuleAnswer {
	this := CreateCourseModuleAnswer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateCourseModuleAnswer) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCourseModuleAnswer) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateCourseModuleAnswer) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateCourseModuleAnswer) SetId(v string) {
	o.Id = &v
}

func (o CreateCourseModuleAnswer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCourseModuleAnswer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableCreateCourseModuleAnswer struct {
	value *CreateCourseModuleAnswer
	isSet bool
}

func (v NullableCreateCourseModuleAnswer) Get() *CreateCourseModuleAnswer {
	return v.value
}

func (v *NullableCreateCourseModuleAnswer) Set(val *CreateCourseModuleAnswer) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCourseModuleAnswer) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCourseModuleAnswer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCourseModuleAnswer(val *CreateCourseModuleAnswer) *NullableCreateCourseModuleAnswer {
	return &NullableCreateCourseModuleAnswer{value: val, isSet: true}
}

func (v NullableCreateCourseModuleAnswer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCourseModuleAnswer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


