/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the SocrateAnswerExample type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SocrateAnswerExample{}

// SocrateAnswerExample struct for SocrateAnswerExample
type SocrateAnswerExample struct {
	Assessments []map[string]interface{} `json:"assessments,omitempty"`
}

// NewSocrateAnswerExample instantiates a new SocrateAnswerExample object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSocrateAnswerExample() *SocrateAnswerExample {
	this := SocrateAnswerExample{}
	return &this
}

// NewSocrateAnswerExampleWithDefaults instantiates a new SocrateAnswerExample object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSocrateAnswerExampleWithDefaults() *SocrateAnswerExample {
	this := SocrateAnswerExample{}
	return &this
}

// GetAssessments returns the Assessments field value if set, zero value otherwise.
func (o *SocrateAnswerExample) GetAssessments() []map[string]interface{} {
	if o == nil || IsNil(o.Assessments) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Assessments
}

// GetAssessmentsOk returns a tuple with the Assessments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocrateAnswerExample) GetAssessmentsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Assessments) {
		return nil, false
	}
	return o.Assessments, true
}

// HasAssessments returns a boolean if a field has been set.
func (o *SocrateAnswerExample) HasAssessments() bool {
	if o != nil && !IsNil(o.Assessments) {
		return true
	}

	return false
}

// SetAssessments gets a reference to the given []map[string]interface{} and assigns it to the Assessments field.
func (o *SocrateAnswerExample) SetAssessments(v []map[string]interface{}) {
	o.Assessments = v
}

func (o SocrateAnswerExample) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SocrateAnswerExample) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Assessments) {
		toSerialize["assessments"] = o.Assessments
	}
	return toSerialize, nil
}

type NullableSocrateAnswerExample struct {
	value *SocrateAnswerExample
	isSet bool
}

func (v NullableSocrateAnswerExample) Get() *SocrateAnswerExample {
	return v.value
}

func (v *NullableSocrateAnswerExample) Set(val *SocrateAnswerExample) {
	v.value = val
	v.isSet = true
}

func (v NullableSocrateAnswerExample) IsSet() bool {
	return v.isSet
}

func (v *NullableSocrateAnswerExample) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSocrateAnswerExample(val *SocrateAnswerExample) *NullableSocrateAnswerExample {
	return &NullableSocrateAnswerExample{value: val, isSet: true}
}

func (v NullableSocrateAnswerExample) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSocrateAnswerExample) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


