/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the AddTeacherToCourse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddTeacherToCourse{}

// AddTeacherToCourse struct for AddTeacherToCourse
type AddTeacherToCourse struct {
	// User identifier
	UserId *string `json:"userId,omitempty"`
	// Teacher access, it will be ignored for org owners.
	ReadOnly *bool `json:"readOnly,omitempty"`
}

// NewAddTeacherToCourse instantiates a new AddTeacherToCourse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTeacherToCourse() *AddTeacherToCourse {
	this := AddTeacherToCourse{}
	return &this
}

// NewAddTeacherToCourseWithDefaults instantiates a new AddTeacherToCourse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTeacherToCourseWithDefaults() *AddTeacherToCourse {
	this := AddTeacherToCourse{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *AddTeacherToCourse) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddTeacherToCourse) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *AddTeacherToCourse) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *AddTeacherToCourse) SetUserId(v string) {
	o.UserId = &v
}

// GetReadOnly returns the ReadOnly field value if set, zero value otherwise.
func (o *AddTeacherToCourse) GetReadOnly() bool {
	if o == nil || IsNil(o.ReadOnly) {
		var ret bool
		return ret
	}
	return *o.ReadOnly
}

// GetReadOnlyOk returns a tuple with the ReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddTeacherToCourse) GetReadOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.ReadOnly) {
		return nil, false
	}
	return o.ReadOnly, true
}

// HasReadOnly returns a boolean if a field has been set.
func (o *AddTeacherToCourse) HasReadOnly() bool {
	if o != nil && !IsNil(o.ReadOnly) {
		return true
	}

	return false
}

// SetReadOnly gets a reference to the given bool and assigns it to the ReadOnly field.
func (o *AddTeacherToCourse) SetReadOnly(v bool) {
	o.ReadOnly = &v
}

func (o AddTeacherToCourse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddTeacherToCourse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.ReadOnly) {
		toSerialize["readOnly"] = o.ReadOnly
	}
	return toSerialize, nil
}

type NullableAddTeacherToCourse struct {
	value *AddTeacherToCourse
	isSet bool
}

func (v NullableAddTeacherToCourse) Get() *AddTeacherToCourse {
	return v.value
}

func (v *NullableAddTeacherToCourse) Set(val *AddTeacherToCourse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTeacherToCourse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTeacherToCourse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTeacherToCourse(val *AddTeacherToCourse) *NullableAddTeacherToCourse {
	return &NullableAddTeacherToCourse{value: val, isSet: true}
}

func (v NullableAddTeacherToCourse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTeacherToCourse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


