/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the TimedExamMode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimedExamMode{}

// TimedExamMode struct for TimedExamMode
type TimedExamMode struct {
	Enabled *bool `json:"enabled,omitempty"`
	Duration *int32 `json:"duration,omitempty"`
}

// NewTimedExamMode instantiates a new TimedExamMode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimedExamMode() *TimedExamMode {
	this := TimedExamMode{}
	return &this
}

// NewTimedExamModeWithDefaults instantiates a new TimedExamMode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimedExamModeWithDefaults() *TimedExamMode {
	this := TimedExamMode{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *TimedExamMode) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimedExamMode) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *TimedExamMode) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *TimedExamMode) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *TimedExamMode) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimedExamMode) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *TimedExamMode) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *TimedExamMode) SetDuration(v int32) {
	o.Duration = &v
}

func (o TimedExamMode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimedExamMode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	return toSerialize, nil
}

type NullableTimedExamMode struct {
	value *TimedExamMode
	isSet bool
}

func (v NullableTimedExamMode) Get() *TimedExamMode {
	return v.value
}

func (v *NullableTimedExamMode) Set(val *TimedExamMode) {
	v.value = val
	v.isSet = true
}

func (v NullableTimedExamMode) IsSet() bool {
	return v.isSet
}

func (v *NullableTimedExamMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimedExamMode(val *TimedExamMode) *NullableTimedExamMode {
	return &NullableTimedExamMode{value: val, isSet: true}
}

func (v NullableTimedExamMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimedExamMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


