/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the StackInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StackInfo{}

// StackInfo struct for StackInfo
type StackInfo struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	LongDescription *string `json:"long_description,omitempty"`
	ShortDescription *string `json:"short_description,omitempty"`
	Owner *string `json:"owner,omitempty"`
	OwnerType *string `json:"owner_type,omitempty"`
	Versions []StackVersionInfo `json:"versions,omitempty"`
	Installations *int64 `json:"installations,omitempty"`
}

// NewStackInfo instantiates a new StackInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackInfo() *StackInfo {
	this := StackInfo{}
	return &this
}

// NewStackInfoWithDefaults instantiates a new StackInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackInfoWithDefaults() *StackInfo {
	this := StackInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StackInfo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackInfo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StackInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *StackInfo) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *StackInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *StackInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *StackInfo) SetName(v string) {
	o.Name = &v
}

// GetLongDescription returns the LongDescription field value if set, zero value otherwise.
func (o *StackInfo) GetLongDescription() string {
	if o == nil || IsNil(o.LongDescription) {
		var ret string
		return ret
	}
	return *o.LongDescription
}

// GetLongDescriptionOk returns a tuple with the LongDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackInfo) GetLongDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.LongDescription) {
		return nil, false
	}
	return o.LongDescription, true
}

// HasLongDescription returns a boolean if a field has been set.
func (o *StackInfo) HasLongDescription() bool {
	if o != nil && !IsNil(o.LongDescription) {
		return true
	}

	return false
}

// SetLongDescription gets a reference to the given string and assigns it to the LongDescription field.
func (o *StackInfo) SetLongDescription(v string) {
	o.LongDescription = &v
}

// GetShortDescription returns the ShortDescription field value if set, zero value otherwise.
func (o *StackInfo) GetShortDescription() string {
	if o == nil || IsNil(o.ShortDescription) {
		var ret string
		return ret
	}
	return *o.ShortDescription
}

// GetShortDescriptionOk returns a tuple with the ShortDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackInfo) GetShortDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.ShortDescription) {
		return nil, false
	}
	return o.ShortDescription, true
}

// HasShortDescription returns a boolean if a field has been set.
func (o *StackInfo) HasShortDescription() bool {
	if o != nil && !IsNil(o.ShortDescription) {
		return true
	}

	return false
}

// SetShortDescription gets a reference to the given string and assigns it to the ShortDescription field.
func (o *StackInfo) SetShortDescription(v string) {
	o.ShortDescription = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *StackInfo) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackInfo) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *StackInfo) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *StackInfo) SetOwner(v string) {
	o.Owner = &v
}

// GetOwnerType returns the OwnerType field value if set, zero value otherwise.
func (o *StackInfo) GetOwnerType() string {
	if o == nil || IsNil(o.OwnerType) {
		var ret string
		return ret
	}
	return *o.OwnerType
}

// GetOwnerTypeOk returns a tuple with the OwnerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackInfo) GetOwnerTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OwnerType) {
		return nil, false
	}
	return o.OwnerType, true
}

// HasOwnerType returns a boolean if a field has been set.
func (o *StackInfo) HasOwnerType() bool {
	if o != nil && !IsNil(o.OwnerType) {
		return true
	}

	return false
}

// SetOwnerType gets a reference to the given string and assigns it to the OwnerType field.
func (o *StackInfo) SetOwnerType(v string) {
	o.OwnerType = &v
}

// GetVersions returns the Versions field value if set, zero value otherwise.
func (o *StackInfo) GetVersions() []StackVersionInfo {
	if o == nil || IsNil(o.Versions) {
		var ret []StackVersionInfo
		return ret
	}
	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackInfo) GetVersionsOk() ([]StackVersionInfo, bool) {
	if o == nil || IsNil(o.Versions) {
		return nil, false
	}
	return o.Versions, true
}

// HasVersions returns a boolean if a field has been set.
func (o *StackInfo) HasVersions() bool {
	if o != nil && !IsNil(o.Versions) {
		return true
	}

	return false
}

// SetVersions gets a reference to the given []StackVersionInfo and assigns it to the Versions field.
func (o *StackInfo) SetVersions(v []StackVersionInfo) {
	o.Versions = v
}

// GetInstallations returns the Installations field value if set, zero value otherwise.
func (o *StackInfo) GetInstallations() int64 {
	if o == nil || IsNil(o.Installations) {
		var ret int64
		return ret
	}
	return *o.Installations
}

// GetInstallationsOk returns a tuple with the Installations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackInfo) GetInstallationsOk() (*int64, bool) {
	if o == nil || IsNil(o.Installations) {
		return nil, false
	}
	return o.Installations, true
}

// HasInstallations returns a boolean if a field has been set.
func (o *StackInfo) HasInstallations() bool {
	if o != nil && !IsNil(o.Installations) {
		return true
	}

	return false
}

// SetInstallations gets a reference to the given int64 and assigns it to the Installations field.
func (o *StackInfo) SetInstallations(v int64) {
	o.Installations = &v
}

func (o StackInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StackInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.LongDescription) {
		toSerialize["long_description"] = o.LongDescription
	}
	if !IsNil(o.ShortDescription) {
		toSerialize["short_description"] = o.ShortDescription
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.OwnerType) {
		toSerialize["owner_type"] = o.OwnerType
	}
	if !IsNil(o.Versions) {
		toSerialize["versions"] = o.Versions
	}
	if !IsNil(o.Installations) {
		toSerialize["installations"] = o.Installations
	}
	return toSerialize, nil
}

type NullableStackInfo struct {
	value *StackInfo
	isSet bool
}

func (v NullableStackInfo) Get() *StackInfo {
	return v.value
}

func (v *NullableStackInfo) Set(val *StackInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableStackInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableStackInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackInfo(val *StackInfo) *NullableStackInfo {
	return &NullableStackInfo{value: val, isSet: true}
}

func (v NullableStackInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


