/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the SocrateTagSearchExample type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SocrateTagSearchExample{}

// SocrateTagSearchExample struct for SocrateTagSearchExample
type SocrateTagSearchExample struct {
	AssessmentType *string `json:"Assessment Type,omitempty"`
	BloomsLevel *string `json:"Bloom's level,omitempty"`
	Content *string `json:"Content,omitempty"`
	ProgrammingLanguage *string `json:"Programming Language,omitempty"`
	LearningObjectives *string `json:"Learning Objectives,omitempty"`
}

// NewSocrateTagSearchExample instantiates a new SocrateTagSearchExample object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSocrateTagSearchExample() *SocrateTagSearchExample {
	this := SocrateTagSearchExample{}
	return &this
}

// NewSocrateTagSearchExampleWithDefaults instantiates a new SocrateTagSearchExample object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSocrateTagSearchExampleWithDefaults() *SocrateTagSearchExample {
	this := SocrateTagSearchExample{}
	return &this
}

// GetAssessmentType returns the AssessmentType field value if set, zero value otherwise.
func (o *SocrateTagSearchExample) GetAssessmentType() string {
	if o == nil || IsNil(o.AssessmentType) {
		var ret string
		return ret
	}
	return *o.AssessmentType
}

// GetAssessmentTypeOk returns a tuple with the AssessmentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocrateTagSearchExample) GetAssessmentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AssessmentType) {
		return nil, false
	}
	return o.AssessmentType, true
}

// HasAssessmentType returns a boolean if a field has been set.
func (o *SocrateTagSearchExample) HasAssessmentType() bool {
	if o != nil && !IsNil(o.AssessmentType) {
		return true
	}

	return false
}

// SetAssessmentType gets a reference to the given string and assigns it to the AssessmentType field.
func (o *SocrateTagSearchExample) SetAssessmentType(v string) {
	o.AssessmentType = &v
}

// GetBloomsLevel returns the BloomsLevel field value if set, zero value otherwise.
func (o *SocrateTagSearchExample) GetBloomsLevel() string {
	if o == nil || IsNil(o.BloomsLevel) {
		var ret string
		return ret
	}
	return *o.BloomsLevel
}

// GetBloomsLevelOk returns a tuple with the BloomsLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocrateTagSearchExample) GetBloomsLevelOk() (*string, bool) {
	if o == nil || IsNil(o.BloomsLevel) {
		return nil, false
	}
	return o.BloomsLevel, true
}

// HasBloomsLevel returns a boolean if a field has been set.
func (o *SocrateTagSearchExample) HasBloomsLevel() bool {
	if o != nil && !IsNil(o.BloomsLevel) {
		return true
	}

	return false
}

// SetBloomsLevel gets a reference to the given string and assigns it to the BloomsLevel field.
func (o *SocrateTagSearchExample) SetBloomsLevel(v string) {
	o.BloomsLevel = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *SocrateTagSearchExample) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocrateTagSearchExample) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *SocrateTagSearchExample) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *SocrateTagSearchExample) SetContent(v string) {
	o.Content = &v
}

// GetProgrammingLanguage returns the ProgrammingLanguage field value if set, zero value otherwise.
func (o *SocrateTagSearchExample) GetProgrammingLanguage() string {
	if o == nil || IsNil(o.ProgrammingLanguage) {
		var ret string
		return ret
	}
	return *o.ProgrammingLanguage
}

// GetProgrammingLanguageOk returns a tuple with the ProgrammingLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocrateTagSearchExample) GetProgrammingLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.ProgrammingLanguage) {
		return nil, false
	}
	return o.ProgrammingLanguage, true
}

// HasProgrammingLanguage returns a boolean if a field has been set.
func (o *SocrateTagSearchExample) HasProgrammingLanguage() bool {
	if o != nil && !IsNil(o.ProgrammingLanguage) {
		return true
	}

	return false
}

// SetProgrammingLanguage gets a reference to the given string and assigns it to the ProgrammingLanguage field.
func (o *SocrateTagSearchExample) SetProgrammingLanguage(v string) {
	o.ProgrammingLanguage = &v
}

// GetLearningObjectives returns the LearningObjectives field value if set, zero value otherwise.
func (o *SocrateTagSearchExample) GetLearningObjectives() string {
	if o == nil || IsNil(o.LearningObjectives) {
		var ret string
		return ret
	}
	return *o.LearningObjectives
}

// GetLearningObjectivesOk returns a tuple with the LearningObjectives field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocrateTagSearchExample) GetLearningObjectivesOk() (*string, bool) {
	if o == nil || IsNil(o.LearningObjectives) {
		return nil, false
	}
	return o.LearningObjectives, true
}

// HasLearningObjectives returns a boolean if a field has been set.
func (o *SocrateTagSearchExample) HasLearningObjectives() bool {
	if o != nil && !IsNil(o.LearningObjectives) {
		return true
	}

	return false
}

// SetLearningObjectives gets a reference to the given string and assigns it to the LearningObjectives field.
func (o *SocrateTagSearchExample) SetLearningObjectives(v string) {
	o.LearningObjectives = &v
}

func (o SocrateTagSearchExample) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SocrateTagSearchExample) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssessmentType) {
		toSerialize["Assessment Type"] = o.AssessmentType
	}
	if !IsNil(o.BloomsLevel) {
		toSerialize["Bloom's level"] = o.BloomsLevel
	}
	if !IsNil(o.Content) {
		toSerialize["Content"] = o.Content
	}
	if !IsNil(o.ProgrammingLanguage) {
		toSerialize["Programming Language"] = o.ProgrammingLanguage
	}
	if !IsNil(o.LearningObjectives) {
		toSerialize["Learning Objectives"] = o.LearningObjectives
	}
	return toSerialize, nil
}

type NullableSocrateTagSearchExample struct {
	value *SocrateTagSearchExample
	isSet bool
}

func (v NullableSocrateTagSearchExample) Get() *SocrateTagSearchExample {
	return v.value
}

func (v *NullableSocrateTagSearchExample) Set(val *SocrateTagSearchExample) {
	v.value = val
	v.isSet = true
}

func (v NullableSocrateTagSearchExample) IsSet() bool {
	return v.isSet
}

func (v *NullableSocrateTagSearchExample) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSocrateTagSearchExample(val *SocrateTagSearchExample) *NullableSocrateTagSearchExample {
	return &NullableSocrateTagSearchExample{value: val, isSet: true}
}

func (v NullableSocrateTagSearchExample) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSocrateTagSearchExample) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


