/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the GigaBoxSlot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GigaBoxSlot{}

// GigaBoxSlot struct for GigaBoxSlot
type GigaBoxSlot struct {
	// Type of the GigaBox
	BoxType *string `json:"boxType,omitempty"`
}

// NewGigaBoxSlot instantiates a new GigaBoxSlot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGigaBoxSlot() *GigaBoxSlot {
	this := GigaBoxSlot{}
	return &this
}

// NewGigaBoxSlotWithDefaults instantiates a new GigaBoxSlot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGigaBoxSlotWithDefaults() *GigaBoxSlot {
	this := GigaBoxSlot{}
	return &this
}

// GetBoxType returns the BoxType field value if set, zero value otherwise.
func (o *GigaBoxSlot) GetBoxType() string {
	if o == nil || IsNil(o.BoxType) {
		var ret string
		return ret
	}
	return *o.BoxType
}

// GetBoxTypeOk returns a tuple with the BoxType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GigaBoxSlot) GetBoxTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BoxType) {
		return nil, false
	}
	return o.BoxType, true
}

// HasBoxType returns a boolean if a field has been set.
func (o *GigaBoxSlot) HasBoxType() bool {
	if o != nil && !IsNil(o.BoxType) {
		return true
	}

	return false
}

// SetBoxType gets a reference to the given string and assigns it to the BoxType field.
func (o *GigaBoxSlot) SetBoxType(v string) {
	o.BoxType = &v
}

func (o GigaBoxSlot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GigaBoxSlot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BoxType) {
		toSerialize["boxType"] = o.BoxType
	}
	return toSerialize, nil
}

type NullableGigaBoxSlot struct {
	value *GigaBoxSlot
	isSet bool
}

func (v NullableGigaBoxSlot) Get() *GigaBoxSlot {
	return v.value
}

func (v *NullableGigaBoxSlot) Set(val *GigaBoxSlot) {
	v.value = val
	v.isSet = true
}

func (v NullableGigaBoxSlot) IsSet() bool {
	return v.isSet
}

func (v *NullableGigaBoxSlot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGigaBoxSlot(val *GigaBoxSlot) *NullableGigaBoxSlot {
	return &NullableGigaBoxSlot{value: val, isSet: true}
}

func (v NullableGigaBoxSlot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGigaBoxSlot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


