/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the ListCourses type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCourses{}

// ListCourses struct for ListCourses
type ListCourses struct {
	// List of courses
	Courses []Course `json:"courses,omitempty"`
	// If specified and not empty - next search data portion token
	NextToken *string `json:"nextToken,omitempty"`
}

// NewListCourses instantiates a new ListCourses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCourses() *ListCourses {
	this := ListCourses{}
	return &this
}

// NewListCoursesWithDefaults instantiates a new ListCourses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCoursesWithDefaults() *ListCourses {
	this := ListCourses{}
	return &this
}

// GetCourses returns the Courses field value if set, zero value otherwise.
func (o *ListCourses) GetCourses() []Course {
	if o == nil || IsNil(o.Courses) {
		var ret []Course
		return ret
	}
	return o.Courses
}

// GetCoursesOk returns a tuple with the Courses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCourses) GetCoursesOk() ([]Course, bool) {
	if o == nil || IsNil(o.Courses) {
		return nil, false
	}
	return o.Courses, true
}

// HasCourses returns a boolean if a field has been set.
func (o *ListCourses) HasCourses() bool {
	if o != nil && !IsNil(o.Courses) {
		return true
	}

	return false
}

// SetCourses gets a reference to the given []Course and assigns it to the Courses field.
func (o *ListCourses) SetCourses(v []Course) {
	o.Courses = v
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *ListCourses) GetNextToken() string {
	if o == nil || IsNil(o.NextToken) {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCourses) GetNextTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextToken) {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *ListCourses) HasNextToken() bool {
	if o != nil && !IsNil(o.NextToken) {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *ListCourses) SetNextToken(v string) {
	o.NextToken = &v
}

func (o ListCourses) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCourses) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Courses) {
		toSerialize["courses"] = o.Courses
	}
	if !IsNil(o.NextToken) {
		toSerialize["nextToken"] = o.NextToken
	}
	return toSerialize, nil
}

type NullableListCourses struct {
	value *ListCourses
	isSet bool
}

func (v NullableListCourses) Get() *ListCourses {
	return v.value
}

func (v *NullableListCourses) Set(val *ListCourses) {
	v.value = val
	v.isSet = true
}

func (v NullableListCourses) IsSet() bool {
	return v.isSet
}

func (v *NullableListCourses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCourses(val *ListCourses) *NullableListCourses {
	return &NullableListCourses{value: val, isSet: true}
}

func (v NullableListCourses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCourses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


