/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the ExamMode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExamMode{}

// ExamMode struct for ExamMode
type ExamMode struct {
	TimedMode *TimedExamMode `json:"timedMode,omitempty"`
	ShuffleQuestionsOrder *bool `json:"shuffleQuestionsOrder,omitempty"`
	ForwardOnlyNavigation *bool `json:"forwardOnlyNavigation,omitempty"`
	SingleLogin *bool `json:"singleLogin,omitempty"`
	Authentication *bool `json:"authentication,omitempty"`
	RestrictedIPRange *RestrictedIPRange `json:"restrictedIPRange,omitempty"`
}

// NewExamMode instantiates a new ExamMode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExamMode() *ExamMode {
	this := ExamMode{}
	return &this
}

// NewExamModeWithDefaults instantiates a new ExamMode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExamModeWithDefaults() *ExamMode {
	this := ExamMode{}
	return &this
}

// GetTimedMode returns the TimedMode field value if set, zero value otherwise.
func (o *ExamMode) GetTimedMode() TimedExamMode {
	if o == nil || IsNil(o.TimedMode) {
		var ret TimedExamMode
		return ret
	}
	return *o.TimedMode
}

// GetTimedModeOk returns a tuple with the TimedMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExamMode) GetTimedModeOk() (*TimedExamMode, bool) {
	if o == nil || IsNil(o.TimedMode) {
		return nil, false
	}
	return o.TimedMode, true
}

// HasTimedMode returns a boolean if a field has been set.
func (o *ExamMode) HasTimedMode() bool {
	if o != nil && !IsNil(o.TimedMode) {
		return true
	}

	return false
}

// SetTimedMode gets a reference to the given TimedExamMode and assigns it to the TimedMode field.
func (o *ExamMode) SetTimedMode(v TimedExamMode) {
	o.TimedMode = &v
}

// GetShuffleQuestionsOrder returns the ShuffleQuestionsOrder field value if set, zero value otherwise.
func (o *ExamMode) GetShuffleQuestionsOrder() bool {
	if o == nil || IsNil(o.ShuffleQuestionsOrder) {
		var ret bool
		return ret
	}
	return *o.ShuffleQuestionsOrder
}

// GetShuffleQuestionsOrderOk returns a tuple with the ShuffleQuestionsOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExamMode) GetShuffleQuestionsOrderOk() (*bool, bool) {
	if o == nil || IsNil(o.ShuffleQuestionsOrder) {
		return nil, false
	}
	return o.ShuffleQuestionsOrder, true
}

// HasShuffleQuestionsOrder returns a boolean if a field has been set.
func (o *ExamMode) HasShuffleQuestionsOrder() bool {
	if o != nil && !IsNil(o.ShuffleQuestionsOrder) {
		return true
	}

	return false
}

// SetShuffleQuestionsOrder gets a reference to the given bool and assigns it to the ShuffleQuestionsOrder field.
func (o *ExamMode) SetShuffleQuestionsOrder(v bool) {
	o.ShuffleQuestionsOrder = &v
}

// GetForwardOnlyNavigation returns the ForwardOnlyNavigation field value if set, zero value otherwise.
func (o *ExamMode) GetForwardOnlyNavigation() bool {
	if o == nil || IsNil(o.ForwardOnlyNavigation) {
		var ret bool
		return ret
	}
	return *o.ForwardOnlyNavigation
}

// GetForwardOnlyNavigationOk returns a tuple with the ForwardOnlyNavigation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExamMode) GetForwardOnlyNavigationOk() (*bool, bool) {
	if o == nil || IsNil(o.ForwardOnlyNavigation) {
		return nil, false
	}
	return o.ForwardOnlyNavigation, true
}

// HasForwardOnlyNavigation returns a boolean if a field has been set.
func (o *ExamMode) HasForwardOnlyNavigation() bool {
	if o != nil && !IsNil(o.ForwardOnlyNavigation) {
		return true
	}

	return false
}

// SetForwardOnlyNavigation gets a reference to the given bool and assigns it to the ForwardOnlyNavigation field.
func (o *ExamMode) SetForwardOnlyNavigation(v bool) {
	o.ForwardOnlyNavigation = &v
}

// GetSingleLogin returns the SingleLogin field value if set, zero value otherwise.
func (o *ExamMode) GetSingleLogin() bool {
	if o == nil || IsNil(o.SingleLogin) {
		var ret bool
		return ret
	}
	return *o.SingleLogin
}

// GetSingleLoginOk returns a tuple with the SingleLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExamMode) GetSingleLoginOk() (*bool, bool) {
	if o == nil || IsNil(o.SingleLogin) {
		return nil, false
	}
	return o.SingleLogin, true
}

// HasSingleLogin returns a boolean if a field has been set.
func (o *ExamMode) HasSingleLogin() bool {
	if o != nil && !IsNil(o.SingleLogin) {
		return true
	}

	return false
}

// SetSingleLogin gets a reference to the given bool and assigns it to the SingleLogin field.
func (o *ExamMode) SetSingleLogin(v bool) {
	o.SingleLogin = &v
}

// GetAuthentication returns the Authentication field value if set, zero value otherwise.
func (o *ExamMode) GetAuthentication() bool {
	if o == nil || IsNil(o.Authentication) {
		var ret bool
		return ret
	}
	return *o.Authentication
}

// GetAuthenticationOk returns a tuple with the Authentication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExamMode) GetAuthenticationOk() (*bool, bool) {
	if o == nil || IsNil(o.Authentication) {
		return nil, false
	}
	return o.Authentication, true
}

// HasAuthentication returns a boolean if a field has been set.
func (o *ExamMode) HasAuthentication() bool {
	if o != nil && !IsNil(o.Authentication) {
		return true
	}

	return false
}

// SetAuthentication gets a reference to the given bool and assigns it to the Authentication field.
func (o *ExamMode) SetAuthentication(v bool) {
	o.Authentication = &v
}

// GetRestrictedIPRange returns the RestrictedIPRange field value if set, zero value otherwise.
func (o *ExamMode) GetRestrictedIPRange() RestrictedIPRange {
	if o == nil || IsNil(o.RestrictedIPRange) {
		var ret RestrictedIPRange
		return ret
	}
	return *o.RestrictedIPRange
}

// GetRestrictedIPRangeOk returns a tuple with the RestrictedIPRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExamMode) GetRestrictedIPRangeOk() (*RestrictedIPRange, bool) {
	if o == nil || IsNil(o.RestrictedIPRange) {
		return nil, false
	}
	return o.RestrictedIPRange, true
}

// HasRestrictedIPRange returns a boolean if a field has been set.
func (o *ExamMode) HasRestrictedIPRange() bool {
	if o != nil && !IsNil(o.RestrictedIPRange) {
		return true
	}

	return false
}

// SetRestrictedIPRange gets a reference to the given RestrictedIPRange and assigns it to the RestrictedIPRange field.
func (o *ExamMode) SetRestrictedIPRange(v RestrictedIPRange) {
	o.RestrictedIPRange = &v
}

func (o ExamMode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExamMode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimedMode) {
		toSerialize["timedMode"] = o.TimedMode
	}
	if !IsNil(o.ShuffleQuestionsOrder) {
		toSerialize["shuffleQuestionsOrder"] = o.ShuffleQuestionsOrder
	}
	if !IsNil(o.ForwardOnlyNavigation) {
		toSerialize["forwardOnlyNavigation"] = o.ForwardOnlyNavigation
	}
	if !IsNil(o.SingleLogin) {
		toSerialize["singleLogin"] = o.SingleLogin
	}
	if !IsNil(o.Authentication) {
		toSerialize["authentication"] = o.Authentication
	}
	if !IsNil(o.RestrictedIPRange) {
		toSerialize["restrictedIPRange"] = o.RestrictedIPRange
	}
	return toSerialize, nil
}

type NullableExamMode struct {
	value *ExamMode
	isSet bool
}

func (v NullableExamMode) Get() *ExamMode {
	return v.value
}

func (v *NullableExamMode) Set(val *ExamMode) {
	v.value = val
	v.isSet = true
}

func (v NullableExamMode) IsSet() bool {
	return v.isSet
}

func (v *NullableExamMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExamMode(val *ExamMode) *NullableExamMode {
	return &NullableExamMode{value: val, isSet: true}
}

func (v NullableExamMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExamMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


