/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the AssignmentProgressItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignmentProgressItem{}

// AssignmentProgressItem struct for AssignmentProgressItem
type AssignmentProgressItem struct {
	// Assignment name
	AssignmentName *string `json:"assignment_name,omitempty"`
	// Module id
	AssignmentId *string `json:"assignment_id,omitempty"`
	Started *bool `json:"started,omitempty"`
	// Assignment progress
	Progress *AssignmentProgress `json:"progress,omitempty"`
}

// NewAssignmentProgressItem instantiates a new AssignmentProgressItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignmentProgressItem() *AssignmentProgressItem {
	this := AssignmentProgressItem{}
	return &this
}

// NewAssignmentProgressItemWithDefaults instantiates a new AssignmentProgressItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignmentProgressItemWithDefaults() *AssignmentProgressItem {
	this := AssignmentProgressItem{}
	return &this
}

// GetAssignmentName returns the AssignmentName field value if set, zero value otherwise.
func (o *AssignmentProgressItem) GetAssignmentName() string {
	if o == nil || IsNil(o.AssignmentName) {
		var ret string
		return ret
	}
	return *o.AssignmentName
}

// GetAssignmentNameOk returns a tuple with the AssignmentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentProgressItem) GetAssignmentNameOk() (*string, bool) {
	if o == nil || IsNil(o.AssignmentName) {
		return nil, false
	}
	return o.AssignmentName, true
}

// HasAssignmentName returns a boolean if a field has been set.
func (o *AssignmentProgressItem) HasAssignmentName() bool {
	if o != nil && !IsNil(o.AssignmentName) {
		return true
	}

	return false
}

// SetAssignmentName gets a reference to the given string and assigns it to the AssignmentName field.
func (o *AssignmentProgressItem) SetAssignmentName(v string) {
	o.AssignmentName = &v
}

// GetAssignmentId returns the AssignmentId field value if set, zero value otherwise.
func (o *AssignmentProgressItem) GetAssignmentId() string {
	if o == nil || IsNil(o.AssignmentId) {
		var ret string
		return ret
	}
	return *o.AssignmentId
}

// GetAssignmentIdOk returns a tuple with the AssignmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentProgressItem) GetAssignmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssignmentId) {
		return nil, false
	}
	return o.AssignmentId, true
}

// HasAssignmentId returns a boolean if a field has been set.
func (o *AssignmentProgressItem) HasAssignmentId() bool {
	if o != nil && !IsNil(o.AssignmentId) {
		return true
	}

	return false
}

// SetAssignmentId gets a reference to the given string and assigns it to the AssignmentId field.
func (o *AssignmentProgressItem) SetAssignmentId(v string) {
	o.AssignmentId = &v
}

// GetStarted returns the Started field value if set, zero value otherwise.
func (o *AssignmentProgressItem) GetStarted() bool {
	if o == nil || IsNil(o.Started) {
		var ret bool
		return ret
	}
	return *o.Started
}

// GetStartedOk returns a tuple with the Started field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentProgressItem) GetStartedOk() (*bool, bool) {
	if o == nil || IsNil(o.Started) {
		return nil, false
	}
	return o.Started, true
}

// HasStarted returns a boolean if a field has been set.
func (o *AssignmentProgressItem) HasStarted() bool {
	if o != nil && !IsNil(o.Started) {
		return true
	}

	return false
}

// SetStarted gets a reference to the given bool and assigns it to the Started field.
func (o *AssignmentProgressItem) SetStarted(v bool) {
	o.Started = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *AssignmentProgressItem) GetProgress() AssignmentProgress {
	if o == nil || IsNil(o.Progress) {
		var ret AssignmentProgress
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentProgressItem) GetProgressOk() (*AssignmentProgress, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *AssignmentProgressItem) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given AssignmentProgress and assigns it to the Progress field.
func (o *AssignmentProgressItem) SetProgress(v AssignmentProgress) {
	o.Progress = &v
}

func (o AssignmentProgressItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignmentProgressItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssignmentName) {
		toSerialize["assignment_name"] = o.AssignmentName
	}
	if !IsNil(o.AssignmentId) {
		toSerialize["assignment_id"] = o.AssignmentId
	}
	if !IsNil(o.Started) {
		toSerialize["started"] = o.Started
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	return toSerialize, nil
}

type NullableAssignmentProgressItem struct {
	value *AssignmentProgressItem
	isSet bool
}

func (v NullableAssignmentProgressItem) Get() *AssignmentProgressItem {
	return v.value
}

func (v *NullableAssignmentProgressItem) Set(val *AssignmentProgressItem) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignmentProgressItem) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignmentProgressItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignmentProgressItem(val *AssignmentProgressItem) *NullableAssignmentProgressItem {
	return &NullableAssignmentProgressItem{value: val, isSet: true}
}

func (v NullableAssignmentProgressItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignmentProgressItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


