/*
Codio API

Documentation APIs v1.0

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codioapi

import (
	"encoding/json"
)

// checks if the StudentTimeExtension type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StudentTimeExtension{}

// StudentTimeExtension struct for StudentTimeExtension
type StudentTimeExtension struct {
	// Extended assignment deadline for student
	ExtendedDeadline *int32 `json:"extendedDeadline,omitempty"`
	// Extended exam time limit for student
	ExtendedTimeLimit *int32 `json:"extendedTimeLimit,omitempty"`
}

// NewStudentTimeExtension instantiates a new StudentTimeExtension object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStudentTimeExtension() *StudentTimeExtension {
	this := StudentTimeExtension{}
	return &this
}

// NewStudentTimeExtensionWithDefaults instantiates a new StudentTimeExtension object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStudentTimeExtensionWithDefaults() *StudentTimeExtension {
	this := StudentTimeExtension{}
	return &this
}

// GetExtendedDeadline returns the ExtendedDeadline field value if set, zero value otherwise.
func (o *StudentTimeExtension) GetExtendedDeadline() int32 {
	if o == nil || IsNil(o.ExtendedDeadline) {
		var ret int32
		return ret
	}
	return *o.ExtendedDeadline
}

// GetExtendedDeadlineOk returns a tuple with the ExtendedDeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentTimeExtension) GetExtendedDeadlineOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtendedDeadline) {
		return nil, false
	}
	return o.ExtendedDeadline, true
}

// HasExtendedDeadline returns a boolean if a field has been set.
func (o *StudentTimeExtension) HasExtendedDeadline() bool {
	if o != nil && !IsNil(o.ExtendedDeadline) {
		return true
	}

	return false
}

// SetExtendedDeadline gets a reference to the given int32 and assigns it to the ExtendedDeadline field.
func (o *StudentTimeExtension) SetExtendedDeadline(v int32) {
	o.ExtendedDeadline = &v
}

// GetExtendedTimeLimit returns the ExtendedTimeLimit field value if set, zero value otherwise.
func (o *StudentTimeExtension) GetExtendedTimeLimit() int32 {
	if o == nil || IsNil(o.ExtendedTimeLimit) {
		var ret int32
		return ret
	}
	return *o.ExtendedTimeLimit
}

// GetExtendedTimeLimitOk returns a tuple with the ExtendedTimeLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StudentTimeExtension) GetExtendedTimeLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtendedTimeLimit) {
		return nil, false
	}
	return o.ExtendedTimeLimit, true
}

// HasExtendedTimeLimit returns a boolean if a field has been set.
func (o *StudentTimeExtension) HasExtendedTimeLimit() bool {
	if o != nil && !IsNil(o.ExtendedTimeLimit) {
		return true
	}

	return false
}

// SetExtendedTimeLimit gets a reference to the given int32 and assigns it to the ExtendedTimeLimit field.
func (o *StudentTimeExtension) SetExtendedTimeLimit(v int32) {
	o.ExtendedTimeLimit = &v
}

func (o StudentTimeExtension) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StudentTimeExtension) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExtendedDeadline) {
		toSerialize["extendedDeadline"] = o.ExtendedDeadline
	}
	if !IsNil(o.ExtendedTimeLimit) {
		toSerialize["extendedTimeLimit"] = o.ExtendedTimeLimit
	}
	return toSerialize, nil
}

type NullableStudentTimeExtension struct {
	value *StudentTimeExtension
	isSet bool
}

func (v NullableStudentTimeExtension) Get() *StudentTimeExtension {
	return v.value
}

func (v *NullableStudentTimeExtension) Set(val *StudentTimeExtension) {
	v.value = val
	v.isSet = true
}

func (v NullableStudentTimeExtension) IsSet() bool {
	return v.isSet
}

func (v *NullableStudentTimeExtension) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStudentTimeExtension(val *StudentTimeExtension) *NullableStudentTimeExtension {
	return &NullableStudentTimeExtension{value: val, isSet: true}
}

func (v NullableStudentTimeExtension) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStudentTimeExtension) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


